// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	admin "getway/biz/router/admin"
	event "getway/biz/router/event"
	market "getway/biz/router/market"
	promo "getway/biz/router/promo"
	show "getway/biz/router/show"
	ticket_type "getway/biz/router/ticket_type"
	user "getway/biz/router/user"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	market.Register(r)

	ticket_type.Register(r)

	show.Register(r)

	promo.Register(r)

	event.Register(r)

	admin.Register(r)

	user.Register(r)

}
