// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: promo/v1/promo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// id SERIAL PRIMARY KEY,
//
//	created_at TIMESTAMP WITH TIME ZONE,
//	updated_at TIMESTAMP WITH TIME ZONE,
//	deleted_at TIMESTAMP WITH TIME ZONE,
//	code VARCHAR(255) UNIQUE NOT NULL,
//	event_id INTEGER,
//	discount_type VARCHAR(50) NOT NULL,
//	discount_value DECIMAL(10,2) NOT NULL,
//	min_amount DECIMAL(10,2) DEFAULT 0,
//	max_uses INTEGER DEFAULT 0,
//	used_count INTEGER DEFAULT 0,
//	start_time TIMESTAMP WITH TIME ZONE,
//	end_time TIMESTAMP WITH TIME ZONE,
//	is_active BOOLEAN DEFAULT true
type CreatePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DiscountType  string                 `protobuf:"bytes,3,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float32                `protobuf:"fixed32,4,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	MinAmount     float32                `protobuf:"fixed32,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxUses       int32                  `protobuf:"varint,6,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UsedCount     int32                  `protobuf:"varint,7,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	StartTime     string                 `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromoRequest) Reset() {
	*x = CreatePromoRequest{}
	mi := &file_promo_v1_promo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoRequest) ProtoMessage() {}

func (x *CreatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoRequest.ProtoReflect.Descriptor instead.
func (*CreatePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePromoRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePromoRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreatePromoRequest) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *CreatePromoRequest) GetDiscountValue() float32 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *CreatePromoRequest) GetMinAmount() float32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CreatePromoRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *CreatePromoRequest) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *CreatePromoRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreatePromoRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreatePromoRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreatePromoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DiscountType  string                 `protobuf:"bytes,3,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float32                `protobuf:"fixed32,4,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	MinAmount     float32                `protobuf:"fixed32,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxUses       int32                  `protobuf:"varint,6,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UsedCount     int32                  `protobuf:"varint,7,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	StartTime     string                 `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromoReply) Reset() {
	*x = CreatePromoReply{}
	mi := &file_promo_v1_promo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoReply) ProtoMessage() {}

func (x *CreatePromoReply) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoReply.ProtoReflect.Descriptor instead.
func (*CreatePromoReply) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePromoReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePromoReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreatePromoReply) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *CreatePromoReply) GetDiscountValue() float32 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *CreatePromoReply) GetMinAmount() float32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CreatePromoReply) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *CreatePromoReply) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *CreatePromoReply) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreatePromoReply) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreatePromoReply) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdatePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	EventId       int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DiscountType  string                 `protobuf:"bytes,4,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float32                `protobuf:"fixed32,5,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	MinAmount     float32                `protobuf:"fixed32,6,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxUses       int32                  `protobuf:"varint,7,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UsedCount     int32                  `protobuf:"varint,8,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	StartTime     string                 `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      *bool                  `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePromoRequest) Reset() {
	*x = UpdatePromoRequest{}
	mi := &file_promo_v1_promo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromoRequest) ProtoMessage() {}

func (x *UpdatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePromoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePromoRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePromoRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *UpdatePromoRequest) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *UpdatePromoRequest) GetDiscountValue() float32 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *UpdatePromoRequest) GetMinAmount() float32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *UpdatePromoRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *UpdatePromoRequest) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *UpdatePromoRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdatePromoRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdatePromoRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type UpdatePromoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	EventId       int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DiscountType  string                 `protobuf:"bytes,4,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float32                `protobuf:"fixed32,5,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	MinAmount     float32                `protobuf:"fixed32,6,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxUses       int32                  `protobuf:"varint,7,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UsedCount     int32                  `protobuf:"varint,8,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	StartTime     string                 `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      *bool                  `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePromoReply) Reset() {
	*x = UpdatePromoReply{}
	mi := &file_promo_v1_promo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromoReply) ProtoMessage() {}

func (x *UpdatePromoReply) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromoReply.ProtoReflect.Descriptor instead.
func (*UpdatePromoReply) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePromoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePromoReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePromoReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *UpdatePromoReply) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *UpdatePromoReply) GetDiscountValue() float32 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *UpdatePromoReply) GetMinAmount() float32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *UpdatePromoReply) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *UpdatePromoReply) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *UpdatePromoReply) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdatePromoReply) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdatePromoReply) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type DeletePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromoRequest) Reset() {
	*x = DeletePromoRequest{}
	mi := &file_promo_v1_promo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromoRequest) ProtoMessage() {}

func (x *DeletePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromoRequest.ProtoReflect.Descriptor instead.
func (*DeletePromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePromoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePromoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromoReply) Reset() {
	*x = DeletePromoReply{}
	mi := &file_promo_v1_promo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromoReply) ProtoMessage() {}

func (x *DeletePromoReply) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromoReply.ProtoReflect.Descriptor instead.
func (*DeletePromoReply) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{5}
}

type GetPromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoRequest) Reset() {
	*x = GetPromoRequest{}
	mi := &file_promo_v1_promo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoRequest) ProtoMessage() {}

func (x *GetPromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoRequest.ProtoReflect.Descriptor instead.
func (*GetPromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{6}
}

func (x *GetPromoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPromoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	EventId       int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DiscountType  string                 `protobuf:"bytes,4,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float32                `protobuf:"fixed32,5,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	MinAmount     float32                `protobuf:"fixed32,6,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxUses       int32                  `protobuf:"varint,7,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UsedCount     int32                  `protobuf:"varint,8,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	StartTime     string                 `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      *bool                  `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoReply) Reset() {
	*x = GetPromoReply{}
	mi := &file_promo_v1_promo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoReply) ProtoMessage() {}

func (x *GetPromoReply) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoReply.ProtoReflect.Descriptor instead.
func (*GetPromoReply) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{7}
}

func (x *GetPromoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPromoReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetPromoReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *GetPromoReply) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *GetPromoReply) GetDiscountValue() float32 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *GetPromoReply) GetMinAmount() float32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *GetPromoReply) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *GetPromoReply) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *GetPromoReply) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetPromoReply) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetPromoReply) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type PromoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	EventId       int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DiscountType  string                 `protobuf:"bytes,4,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float32                `protobuf:"fixed32,5,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	MinAmount     float32                `protobuf:"fixed32,6,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxUses       int32                  `protobuf:"varint,7,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UsedCount     int32                  `protobuf:"varint,8,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	StartTime     string                 `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      *bool                  `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoData) Reset() {
	*x = PromoData{}
	mi := &file_promo_v1_promo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoData) ProtoMessage() {}

func (x *PromoData) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoData.ProtoReflect.Descriptor instead.
func (*PromoData) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{8}
}

func (x *PromoData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PromoData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PromoData) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *PromoData) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *PromoData) GetDiscountValue() float32 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *PromoData) GetMinAmount() float32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *PromoData) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *PromoData) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *PromoData) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *PromoData) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *PromoData) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type ListPromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromoRequest) Reset() {
	*x = ListPromoRequest{}
	mi := &file_promo_v1_promo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromoRequest) ProtoMessage() {}

func (x *ListPromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromoRequest.ProtoReflect.Descriptor instead.
func (*ListPromoRequest) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{9}
}

func (x *ListPromoRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPromoRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListPromoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PromoData           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromoReply) Reset() {
	*x = ListPromoReply{}
	mi := &file_promo_v1_promo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromoReply) ProtoMessage() {}

func (x *ListPromoReply) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromoReply.ProtoReflect.Descriptor instead.
func (*ListPromoReply) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{10}
}

func (x *ListPromoReply) GetList() []*PromoData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListPromoReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ValidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidRequest) Reset() {
	*x = ValidRequest{}
	mi := &file_promo_v1_promo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidRequest) ProtoMessage() {}

func (x *ValidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidRequest.ProtoReflect.Descriptor instead.
func (*ValidRequest) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{11}
}

func (x *ValidRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ValiReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	DiscountType  string                 `protobuf:"bytes,2,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float32                `protobuf:"fixed32,3,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	Discount      float32                `protobuf:"fixed32,4,opt,name=discount,proto3" json:"discount,omitempty"`
	FinalAmount   float32                `protobuf:"fixed32,5,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValiReply) Reset() {
	*x = ValiReply{}
	mi := &file_promo_v1_promo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValiReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValiReply) ProtoMessage() {}

func (x *ValiReply) ProtoReflect() protoreflect.Message {
	mi := &file_promo_v1_promo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValiReply.ProtoReflect.Descriptor instead.
func (*ValiReply) Descriptor() ([]byte, []int) {
	return file_promo_v1_promo_proto_rawDescGZIP(), []int{12}
}

func (x *ValiReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValiReply) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *ValiReply) GetDiscountValue() float32 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *ValiReply) GetDiscount() float32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *ValiReply) GetFinalAmount() float32 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

var File_promo_v1_promo_proto protoreflect.FileDescriptor

const file_promo_v1_promo_proto_rawDesc = "" +
	"\n" +
	"\x14promo/v1/promo.proto\x12\fapi.promo.v1\"\xbf\x02\n" +
	"\x12CreatePromoRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12#\n" +
	"\rdiscount_type\x18\x03 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x04 \x01(\x02R\rdiscountValue\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x05 \x01(\x02R\tminAmount\x12\x19\n" +
	"\bmax_uses\x18\x06 \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"used_count\x18\a \x01(\x05R\tusedCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\tR\aendTime\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"\xbd\x02\n" +
	"\x10CreatePromoReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12#\n" +
	"\rdiscount_type\x18\x03 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x04 \x01(\x02R\rdiscountValue\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x05 \x01(\x02R\tminAmount\x12\x19\n" +
	"\bmax_uses\x18\x06 \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"used_count\x18\a \x01(\x05R\tusedCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\tR\aendTime\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"\xe2\x02\n" +
	"\x12UpdatePromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12#\n" +
	"\rdiscount_type\x18\x04 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x05 \x01(\x02R\rdiscountValue\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x06 \x01(\x02R\tminAmount\x12\x19\n" +
	"\bmax_uses\x18\a \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"used_count\x18\b \x01(\x05R\tusedCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\n" +
	" \x01(\tR\aendTime\x12 \n" +
	"\tis_active\x18\v \x01(\bH\x00R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_is_active\"\xe0\x02\n" +
	"\x10UpdatePromoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12#\n" +
	"\rdiscount_type\x18\x04 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x05 \x01(\x02R\rdiscountValue\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x06 \x01(\x02R\tminAmount\x12\x19\n" +
	"\bmax_uses\x18\a \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"used_count\x18\b \x01(\x05R\tusedCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\n" +
	" \x01(\tR\aendTime\x12 \n" +
	"\tis_active\x18\v \x01(\bH\x00R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_is_active\"$\n" +
	"\x12DeletePromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x12\n" +
	"\x10DeletePromoReply\"!\n" +
	"\x0fGetPromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xdd\x02\n" +
	"\rGetPromoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12#\n" +
	"\rdiscount_type\x18\x04 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x05 \x01(\x02R\rdiscountValue\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x06 \x01(\x02R\tminAmount\x12\x19\n" +
	"\bmax_uses\x18\a \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"used_count\x18\b \x01(\x05R\tusedCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\n" +
	" \x01(\tR\aendTime\x12 \n" +
	"\tis_active\x18\v \x01(\bH\x00R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_is_active\"\xd9\x02\n" +
	"\tPromoData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12#\n" +
	"\rdiscount_type\x18\x04 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x05 \x01(\x02R\rdiscountValue\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x06 \x01(\x02R\tminAmount\x12\x19\n" +
	"\bmax_uses\x18\a \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"used_count\x18\b \x01(\x05R\tusedCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\n" +
	" \x01(\tR\aendTime\x12 \n" +
	"\tis_active\x18\v \x01(\bH\x00R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_is_active\":\n" +
	"\x10ListPromoRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"S\n" +
	"\x0eListPromoReply\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.api.promo.v1.PromoDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\":\n" +
	"\fValidRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\"\xaa\x01\n" +
	"\tValiReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rdiscount_type\x18\x02 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x03 \x01(\x02R\rdiscountValue\x12\x1a\n" +
	"\bdiscount\x18\x04 \x01(\x02R\bdiscount\x12!\n" +
	"\ffinal_amount\x18\x05 \x01(\x02R\vfinalAmount2\xd3\x03\n" +
	"\x05Promo\x12O\n" +
	"\vCreatePromo\x12 .api.promo.v1.CreatePromoRequest\x1a\x1e.api.promo.v1.CreatePromoReply\x12O\n" +
	"\vUpdatePromo\x12 .api.promo.v1.UpdatePromoRequest\x1a\x1e.api.promo.v1.UpdatePromoReply\x12O\n" +
	"\vDeletePromo\x12 .api.promo.v1.DeletePromoRequest\x1a\x1e.api.promo.v1.DeletePromoReply\x12F\n" +
	"\bGetPromo\x12\x1d.api.promo.v1.GetPromoRequest\x1a\x1b.api.promo.v1.GetPromoReply\x12I\n" +
	"\tListPromo\x12\x1e.api.promo.v1.ListPromoRequest\x1a\x1c.api.promo.v1.ListPromoReply\x12D\n" +
	"\rVaildatePromo\x12\x1a.api.promo.v1.ValidRequest\x1a\x17.api.promo.v1.ValiReplyB'\n" +
	"\fapi.promo.v1P\x01Z\x15admin/api/promo/v1;v1b\x06proto3"

var (
	file_promo_v1_promo_proto_rawDescOnce sync.Once
	file_promo_v1_promo_proto_rawDescData []byte
)

func file_promo_v1_promo_proto_rawDescGZIP() []byte {
	file_promo_v1_promo_proto_rawDescOnce.Do(func() {
		file_promo_v1_promo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_promo_v1_promo_proto_rawDesc), len(file_promo_v1_promo_proto_rawDesc)))
	})
	return file_promo_v1_promo_proto_rawDescData
}

var file_promo_v1_promo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_promo_v1_promo_proto_goTypes = []any{
	(*CreatePromoRequest)(nil), // 0: api.promo.v1.CreatePromoRequest
	(*CreatePromoReply)(nil),   // 1: api.promo.v1.CreatePromoReply
	(*UpdatePromoRequest)(nil), // 2: api.promo.v1.UpdatePromoRequest
	(*UpdatePromoReply)(nil),   // 3: api.promo.v1.UpdatePromoReply
	(*DeletePromoRequest)(nil), // 4: api.promo.v1.DeletePromoRequest
	(*DeletePromoReply)(nil),   // 5: api.promo.v1.DeletePromoReply
	(*GetPromoRequest)(nil),    // 6: api.promo.v1.GetPromoRequest
	(*GetPromoReply)(nil),      // 7: api.promo.v1.GetPromoReply
	(*PromoData)(nil),          // 8: api.promo.v1.PromoData
	(*ListPromoRequest)(nil),   // 9: api.promo.v1.ListPromoRequest
	(*ListPromoReply)(nil),     // 10: api.promo.v1.ListPromoReply
	(*ValidRequest)(nil),       // 11: api.promo.v1.ValidRequest
	(*ValiReply)(nil),          // 12: api.promo.v1.ValiReply
}
var file_promo_v1_promo_proto_depIdxs = []int32{
	8,  // 0: api.promo.v1.ListPromoReply.list:type_name -> api.promo.v1.PromoData
	0,  // 1: api.promo.v1.Promo.CreatePromo:input_type -> api.promo.v1.CreatePromoRequest
	2,  // 2: api.promo.v1.Promo.UpdatePromo:input_type -> api.promo.v1.UpdatePromoRequest
	4,  // 3: api.promo.v1.Promo.DeletePromo:input_type -> api.promo.v1.DeletePromoRequest
	6,  // 4: api.promo.v1.Promo.GetPromo:input_type -> api.promo.v1.GetPromoRequest
	9,  // 5: api.promo.v1.Promo.ListPromo:input_type -> api.promo.v1.ListPromoRequest
	11, // 6: api.promo.v1.Promo.VaildatePromo:input_type -> api.promo.v1.ValidRequest
	1,  // 7: api.promo.v1.Promo.CreatePromo:output_type -> api.promo.v1.CreatePromoReply
	3,  // 8: api.promo.v1.Promo.UpdatePromo:output_type -> api.promo.v1.UpdatePromoReply
	5,  // 9: api.promo.v1.Promo.DeletePromo:output_type -> api.promo.v1.DeletePromoReply
	7,  // 10: api.promo.v1.Promo.GetPromo:output_type -> api.promo.v1.GetPromoReply
	10, // 11: api.promo.v1.Promo.ListPromo:output_type -> api.promo.v1.ListPromoReply
	12, // 12: api.promo.v1.Promo.VaildatePromo:output_type -> api.promo.v1.ValiReply
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_promo_v1_promo_proto_init() }
func file_promo_v1_promo_proto_init() {
	if File_promo_v1_promo_proto != nil {
		return
	}
	file_promo_v1_promo_proto_msgTypes[2].OneofWrappers = []any{}
	file_promo_v1_promo_proto_msgTypes[3].OneofWrappers = []any{}
	file_promo_v1_promo_proto_msgTypes[7].OneofWrappers = []any{}
	file_promo_v1_promo_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_promo_v1_promo_proto_rawDesc), len(file_promo_v1_promo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_promo_v1_promo_proto_goTypes,
		DependencyIndexes: file_promo_v1_promo_proto_depIdxs,
		MessageInfos:      file_promo_v1_promo_proto_msgTypes,
	}.Build()
	File_promo_v1_promo_proto = out.File
	file_promo_v1_promo_proto_goTypes = nil
	file_promo_v1_promo_proto_depIdxs = nil
}
