// Code generated by hertz generator.

package market

import (
	"getway/mvw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _marketplaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listactivelistingsMw() []app.HandlerFunc {
	// your code...
	return mvw.AuthMiddleware()
}

func _listmylistingsMw() []app.HandlerFunc {
	// your code...
	return mvw.AuthMiddleware()
}

func _listmypurchasesMw() []app.HandlerFunc {
	// your code...
	return mvw.AuthMiddleware()
}

func _eventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listeventlistingsMw() []app.HandlerFunc {
	// your code...
	return mvw.AuthMiddleware()
}

func _marketplace0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createlistingMw() []app.HandlerFunc {
	// your code...
	return mvw.AuthMiddleware()
}

func _getlistingMw() []app.HandlerFunc {
	// your code...
	return mvw.AuthMiddleware()
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _buylistingMw() []app.HandlerFunc {
	// your code...
	return mvw.AuthMiddleware()
}

func _cancellistingMw() []app.HandlerFunc {
	// your code...
	return mvw.AuthMiddleware()
}

func _transferMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtransferhistoryMw() []app.HandlerFunc {
	// your code...
	return mvw.AuthMiddleware()
}
