// Code generated by hertz generator.

package event

import (
	"getway/mvw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return mvw.AuthMiddleware()
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listeventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteeventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _events0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _geteventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _purchaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _geteventstockMw() []app.HandlerFunc {
	// your code...
	return nil
}
