// Code generated by hertz generator.

package ticket_type

import (
	tktypev1 "activity/api/ticket_type/v1"
	"context"

	"getway/biz/client"
	"getway/biz/handler/response"
	ticket_type "getway/biz/model/ticket_type"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// GetTicketType .
// @router /api/ticket-types/:id [GET]
func GetTicketType(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ticket_type.GetTicketTypeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	res, err := client.GetTicketType().GetTicketType(ctx, &tktypev1.GetTicketTypeRequest{
		Id: req.GetId(),
	})
	if err != nil {
		hlog.Error(err.Error())
		response.HandleBussinessFail(c, err.Error())
		return
	}
	resp := &ticket_type.GetTicketTypeResp{
		Id:         res.GetId(),
		Name:       res.GetName(),
		Price:      res.GetPrice(),
		Stock:      res.GetStock(),
		MaxPerUser: res.GetMaxPerUser(),
		SortOrder:  res.GetSortOrder(),
		EventId:    res.GetEventId(),
	}
	response.HandleSuccess(c, resp)
}

// ListTicketType .
// @router /api/ticket-types [GET]
func ListTicketType(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ticket_type.ListTicketTypeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	res, err := client.GetTicketType().ListTicketType(ctx, &tktypev1.ListTicketTypeRequest{
		Page: req.GetPage(),
		Size: req.GetSize(),
	})
	if err != nil {
		hlog.Error(err.Error())
		response.HandleBussinessFail(c, err.Error())
		return
	}
	list := make([]*ticket_type.TicketTypeData, 0, len(res.GetList()))
	for _, it := range res.GetList() {
		list = append(list, &ticket_type.TicketTypeData{
			Id:         it.GetId(),
			Name:       it.GetName(),
			Price:      it.GetPrice(),
			Stock:      it.GetStock(),
			MaxPerUser: it.GetMaxPerUser(),
			SortOrder:  it.GetSortOrder(),
			EventId:    it.GetEventId(),
		})
	}
	resp := &ticket_type.ListTicketTypeResp{
		List:  list,
		Total: res.GetTotal(),
	}
	response.HandleSuccess(c, resp)
}
