import { theme as antdTheme } from 'antd'

const sharedComponents = {
  Button: {
    primaryShadow: 'none',
    defaultShadow: 'none',
    borderRadius: 4,
    controlHeight: 40,
    controlHeightLG: 48,
    fontWeight: 500,
    borderColorDisabled: '#E5E5E5',
  },
  Card: {
    borderRadiusLG: 0,
    paddingLG: 24,
    paddingSM: 16,
  },
  Input: {
    controlHeight: 40,
    borderRadius: 4,
  },
  Select: {
    controlHeight: 40,
    borderRadius: 4,
  },
  Modal: {
    borderRadiusLG: 0,
    titleFontSize: 18,
  },
  Tag: {
    borderRadiusSM: 2,
  },
  Table: {
    borderRadiusLG: 0,
    cellPaddingInline: 16,
    cellPaddingBlock: 12,
  },
}

export const lightTheme = {
  token: {
    colorPrimary: '#0066FF',
    colorSuccess: '#10B981',
    colorWarning: '#F59E0B',
    colorError: '#EF4444',
    colorInfo: '#0066FF',
    colorBgBase: '#FAFAFA',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#FAFAFA',
    colorText: '#0A0A0A',
    colorTextSecondary: '#666666',
    colorBorder: '#E5E5E5',
    colorBorderSecondary: '#F0F0F0',
    borderRadius: 4,
    borderRadiusLG: 4,
    borderRadiusSM: 2,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'PingFang SC', 'Microsoft YaHei', sans-serif",
    fontSize: 14,
    fontSizeHeading1: 48,
    fontSizeHeading2: 32,
    fontSizeHeading3: 20,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    boxShadow: 'none',
    boxShadowSecondary: '0 1px 3px rgba(0, 0, 0, 0.06)',
    colorLink: '#0066FF',
    colorLinkHover: '#3388FF',
    colorLinkActive: '#0052CC',
    lineHeight: 1.6,
  },
  components: {
    ...sharedComponents,
    Menu: {
      darkItemBg: '#0A0A0A',
      darkSubMenuItemBg: '#141414',
      darkItemSelectedBg: 'rgba(0, 102, 255, 0.15)',
      itemBorderRadius: 4,
      itemMarginInline: 8,
      itemHeight: 40,
      iconSize: 18,
    },
    Table: {
      ...sharedComponents.Table,
      headerBg: '#FAFAFA',
      headerColor: '#666666',
      rowHoverBg: '#F5F5F5',
    },
    Tabs: {
      inkBarColor: '#0A0A0A',
      itemActiveColor: '#0A0A0A',
      itemSelectedColor: '#0A0A0A',
      itemColor: '#999999',
      itemHoverColor: '#666666',
    },
    Descriptions: {
      labelColor: '#999999',
      contentColor: '#0A0A0A',
    },
    Form: {
      labelColor: '#666666',
      labelFontSize: 13,
    },
    Breadcrumb: {
      separatorColor: '#CCCCCC',
      itemColor: '#999999',
      lastItemColor: '#0A0A0A',
    },
    Statistic: {
      titleFontSize: 13,
      contentFontSize: 32,
    },
  },
}

export const darkTheme = {
  algorithm: antdTheme.darkAlgorithm,
  token: {
    colorPrimary: '#3388FF',
    colorSuccess: '#10B981',
    colorWarning: '#F59E0B',
    colorError: '#EF4444',
    colorInfo: '#3388FF',
    colorBgBase: '#0A0A0A',
    colorBgContainer: '#141414',
    colorBgElevated: '#1A1A1A',
    colorBgLayout: '#0A0A0A',
    colorText: '#F5F5F5',
    colorTextSecondary: '#999999',
    colorBorder: '#262626',
    colorBorderSecondary: '#1A1A1A',
    borderRadius: 4,
    borderRadiusLG: 4,
    borderRadiusSM: 2,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'PingFang SC', 'Microsoft YaHei', sans-serif",
    fontSize: 14,
    fontSizeHeading1: 48,
    fontSizeHeading2: 32,
    fontSizeHeading3: 20,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    boxShadow: 'none',
    boxShadowSecondary: '0 1px 3px rgba(0, 0, 0, 0.3)',
    colorLink: '#3388FF',
    colorLinkHover: '#5599FF',
    colorLinkActive: '#2277EE',
    lineHeight: 1.6,
  },
  components: {
    ...sharedComponents,
    Menu: {
      darkItemBg: '#0A0A0A',
      darkSubMenuItemBg: '#141414',
      darkItemSelectedBg: 'rgba(51, 136, 255, 0.15)',
      itemBorderRadius: 4,
      itemMarginInline: 8,
      itemHeight: 40,
      iconSize: 18,
    },
    Table: {
      ...sharedComponents.Table,
      headerBg: '#141414',
      rowHoverBg: '#1A1A1A',
    },
    Tabs: {
      inkBarColor: '#F5F5F5',
      itemActiveColor: '#F5F5F5',
      itemSelectedColor: '#F5F5F5',
      itemColor: '#666666',
      itemHoverColor: '#999999',
    },
    Descriptions: {
      labelColor: '#666666',
      contentColor: '#F5F5F5',
    },
    Form: {
      labelColor: '#999999',
      labelFontSize: 13,
    },
    Breadcrumb: {
      separatorColor: '#444444',
      itemColor: '#666666',
      lastItemColor: '#F5F5F5',
    },
    Statistic: {
      titleFontSize: 13,
      contentFontSize: 32,
    },
  },
}
