// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"sale/pkg/conf"
	"seckill/internal/biz"
	"seckill/internal/data"
	"seckill/internal/server"
	"seckill/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	seckillRepo := data.NewSkillRepo(dataData, logger)
	rdbRepo := data.NewRdbRepo(dataData, logger)
	seckillUseCase := biz.NewSeckillUseCase(confData, seckillRepo, rdbRepo, logger)
	seckillService := service.NewSeckillService(seckillUseCase)
	grpcServer := server.NewGRPCServer(confServer, logger, seckillService)
	consumerUseCase := biz.NewConsumerUseCase(seckillRepo, rdbRepo, logger)
	consumerServer, err := server.NewConsumerServer(confData, consumerUseCase, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, consumerServer)
	return app, func() {
		cleanup()
	}, nil
}
