// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"activity/internal/biz"
	"activity/internal/data"
	"activity/internal/server"
	"activity/internal/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"sale/pkg/conf"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	eventRepo := data.NewEventRepo(dataData, logger)
	ticketTypeRepo := data.NewTicketTypeRepo(dataData, logger)
	eventUseCase := biz.NewEventUseCase(eventRepo, ticketTypeRepo, logger)
	eventService := service.NewEventService(eventUseCase)
	promoRepo := data.NewPromoRepo(dataData, logger)
	promoUseCase := biz.NewPromoUseCase(promoRepo, logger)
	promoService := service.NewPromoService(promoUseCase)
	showRepo := data.NewShowRepo(dataData, logger)
	showUseCase := biz.NewShowUseCase(showRepo, logger)
	showService := service.NewShowService(showUseCase)
	statsRepo := data.NewStatsRepo(dataData, logger)
	statsUseCase := biz.NewStatsUseCase(statsRepo, logger)
	statsService := service.NewStatsService(statsUseCase)
	ticketTypeUseCase := biz.NewTicketTypeUseCase(ticketTypeRepo, logger)
	ticketTypeService := service.NewTicketTypeService(ticketTypeUseCase)
	transferRepo := data.NewTransferRepo(dataData, logger)
	transferUseCase := biz.NewTransferUseCase(transferRepo, logger)
	transferService := service.NewTransferService(transferUseCase)
	grpcServer := server.NewGRPCServer(confServer, logger, eventService, promoService, showService, statsService, ticketTypeService, transferService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
