// Code generated by hertz generator.

package admin

import (
	eventv1 "activity/api/event/v1"
	promov1 "activity/api/promo/v1"
	showv1 "activity/api/show/v1"
	tktypev1 "activity/api/ticket_type/v1"
	"context"
	"getway/biz/client"
	"getway/biz/handler/response"
	admin "getway/biz/model/admin"
	"sale/model"
	v1 "user/api/user/v1"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UpdateUserRole .
// @router /admin/users/role [POST]
func UpdateUserRole(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.UpdateUserRoleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	_, err = client.GetUserClient().UpdateUser(ctx, &v1.UpdateUserRequest{
		UserId: req.UserId,
		Role:   req.Role,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	c.JSON(consts.StatusOK, admin.Empty{})
}

// CreateEvent .
// @router /admin/events [POST]
func CreateEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CreateEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	res, err := client.GetEvent().CreateEvent(ctx, &eventv1.CreateEventRequest{
		Title:       req.Title,
		Description: req.Description,
		Location:    req.Location,
		StartTime:   req.StartTime,
		EndTime:     req.EndTime,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	resp := &admin.CreateEventResp{
		Id:        res.Id,
		Title:     res.Title,
		StartTime: res.StartTime,
		EndTime:   res.EndTime,
		Status:    res.Status,
	}
	response.HandleSuccess(c, &resp)
}

// UpdateEvent .
// @router /admin/events/:id [PUT]
func UpdateEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.UpdateEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}
	res, err := client.GetEvent().UpdateEvent(ctx, &eventv1.UpdateEventRequest{
		Title:       req.Title,
		Description: req.Description,
		Location:    req.Location,
		StartTime:   req.StartTime,
		EndTime:     req.EndTime,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	// resp := new(admin.UpdateEventResp)
	resp := admin.UpdateEventResp{
		Title:     res.Title,
		Location:  res.Location,
		Id:        req.Id,
		StartTime: res.StartTime,
		EndTime:   res.EndTime,
	}

	response.HandleSuccess(c, &resp)
}

// PublishEvent .
// @router /admin/events/:id/publish [POST]
func PublishEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.PublishEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	_, err = client.GetEvent().UpdateStatusEvent(ctx, &eventv1.UpdateStatusRequest{
		Id:     req.GetId(),
		Status: model.EventStatusOnSale,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// UnPublishEvent .
// @router /admin/events/:id/unpublish [POST]
func UnPublishEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.UnPublishEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	_, err = client.GetEvent().UpdateStatusEvent(ctx, &eventv1.UpdateStatusRequest{
		Id:     req.GetId(),
		Status: model.EventStatusOffSale,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// EndEvent .
// @router /admin/events/:id/end [POST]
func EndEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.EndEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	_, err = client.GetEvent().UpdateStatusEvent(ctx, &eventv1.UpdateStatusRequest{
		Id:     req.GetId(),
		Status: model.EventStatusEnded,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// CreateTicketType .
// @router /admin/events/:id/ticket-types [POST]
func CreateTicketType(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CreateTicketTypeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	_, err = client.GetTicketType().CreateTicketType(ctx, &tktypev1.CreateTicketTypeRequest{
		EventId:    req.GetId(),
		Name:       req.GetName(),
		Price:      float32(req.GetPrice()),
		Stock:      req.GetStock(),
		MaxPerUser: req.MaxPerUser,
		SortOrder:  req.SortOrder,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// UpdateTicketType .
// @router /admin/events/ticket-types/:id [PUT]
func UpdateTicketType(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.UpdateTicketTypeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	_, err = client.GetTicketType().UpdateTicketType(ctx, &tktypev1.UpdateTicketTypeRequest{
		Id:         req.GetId(),
		Price:      float32(req.Price),
		Stock:      req.Stock,
		MaxPerUser: req.MaxPerUser,
		SortOrder:  req.SortOrder,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// DeleteTicketType .
// @router /admin/events/ticket-types/:id [DELETE]
func DeleteTicketType(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DeleteTicketTypeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	_, err = client.GetTicketType().DeleteTicketType(ctx, &tktypev1.DeleteTicketTypeRequest{
		Id: req.GetId(),
	})

	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// CreateShow .
// @router /admin/events/:id/shows [POST]
func CreateShow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CreateShowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	_, err = client.GetShow().CreateShow(ctx, &showv1.CreateShowRequest{
		EventId:   req.GetId(),
		Name:      req.Name,
		ShowTime:  req.ShowTime,
		EndTime:   req.EndTime,
		Stock:     req.Stock,
		SortOrder: req.GetSortOrder(),
	})

	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// UpdateShow .
// @router /admin/events/shows/:id [PUT]
func UpdateShow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.UpdateShowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}
	_, err = client.GetShow().UpdateShow(ctx, &showv1.UpdateShowRequest{
		Id:        req.GetId(),
		Name:      req.Name,
		ShowTime:  req.ShowTime,
		EndTime:   req.EndTime,
		Stock:     req.Stock,
		SortOrder: req.SortOrder,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// DeleteShow .
// @router /admin/events/shows/:id [DELETE]
func DeleteShow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DeleteShowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}
	_, err = client.GetShow().DeleteShow(ctx, &showv1.DeleteShowRequest{
		Id: req.GetId(),
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// PublishShow .
// @router /admin/events/shows/:id/publish [POST]
func PublishShow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.PublishShowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}
	_, err = client.GetShow().UpdateStatus(ctx, &showv1.UpdateStatusRequest{
		Id:     req.GetId(),
		Status: model.EventStatusOnSale,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// UnPublishShow .
// @router /admin/events/shows/:id/unpublish [POST]
func UnPublishShow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.UnPublishShowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}
	_, err = client.GetShow().UpdateStatus(ctx, &showv1.UpdateStatusRequest{
		Id:     req.GetId(),
		Status: model.EventStatusOffSale,
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// CreatePromoCode .
// @router /admin/promo [POST]
func CreatePromoCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CreatePromoCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}
	_, err = client.GetPromo().CreatePromo(ctx, &promov1.CreatePromoRequest{
		EventId:       req.GetEventId(),
		Code:          req.GetCode(),
		StartTime:     req.StartTime,
		EndTime:       req.EndTime,
		DiscountType:  req.DiscountType,
		DiscountValue: float32(req.DiscountValue),
		MinAmount:     float32(req.MinAmount),
		MaxUses:       req.GetMaxUses(),
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// DeletePromoCode .
// @router /admin/promo/:id [DELETE]
func DeletePromoCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DeletePromoCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}
	_, err = client.GetPromo().DeletePromo(ctx, &promov1.DeletePromoRequest{
		Id: req.GetId(),
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &admin.Empty{})
}

// GetDashboardStats .
// @router /admin/stats/dashboard [GET]
func GetDashboardStats(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetDashboardStatsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	resp := new(admin.GetDashboardStatsResp)

	c.JSON(consts.StatusOK, resp)
}

// GetSalesTrend .
// @router /admin/stats/sales-trend [GET]
func GetSalesTrend(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetSalesTrendReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	resp := new(admin.GetSalesTrendResp)

	c.JSON(consts.StatusOK, resp)
}

// GetTicketTypeStats .
// @router /admin/stats/ticket-types [GET]
func GetTicketTypeStats(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetTicketTypeStatsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	resp := new(admin.GetTicketTypeStatsResp)

	c.JSON(consts.StatusOK, resp)
}

// GetConversionFunnel .
// @router /admin/stats/funnel/:event_id [GET]
func GetConversionFunnel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetConversionFunnelReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	resp := new(admin.GetConversionFunnelResp)

	c.JSON(consts.StatusOK, resp)
}

// GetPendingTransfers .
// @router /admin/transfer/pending [GET]
func GetPendingTransfers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetPendingTransfersReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	resp := new(admin.GetPendingTransfersResp)

	c.JSON(consts.StatusOK, resp)
}

// ApproveTransfer .
// @router /admin/transfer/:id/approve [POST]
func ApproveTransfer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.ApproveTransferReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	resp := new(admin.MessageResp)

	c.JSON(consts.StatusOK, resp)
}

// RejectTransfer .
// @router /admin/transfer/:id/reject [POST]
func RejectTransfer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.RejectTransferReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	resp := new(admin.MessageResp)

	c.JSON(consts.StatusOK, resp)
}
