// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ticket_type/v1/ticket_type.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTicketTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,5,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketTypeRequest) Reset() {
	*x = CreateTicketTypeRequest{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketTypeRequest) ProtoMessage() {}

func (x *CreateTicketTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketTypeRequest) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTicketTypeRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateTicketTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTicketTypeRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTicketTypeRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateTicketTypeRequest) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *CreateTicketTypeRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateTicketTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,5,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	EventId       int64                  `protobuf:"varint,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketTypeReply) Reset() {
	*x = CreateTicketTypeReply{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketTypeReply) ProtoMessage() {}

func (x *CreateTicketTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketTypeReply.ProtoReflect.Descriptor instead.
func (*CreateTicketTypeReply) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketTypeReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateTicketTypeReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTicketTypeReply) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTicketTypeReply) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateTicketTypeReply) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *CreateTicketTypeReply) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateTicketTypeReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type UpdateTicketTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,5,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	EventId       int64                  `protobuf:"varint,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketTypeRequest) Reset() {
	*x = UpdateTicketTypeRequest{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketTypeRequest) ProtoMessage() {}

func (x *UpdateTicketTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketTypeRequest) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTicketTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTicketTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTicketTypeRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTicketTypeRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateTicketTypeRequest) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *UpdateTicketTypeRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdateTicketTypeRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type UpdateTicketTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,5,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	EventId       int64                  `protobuf:"varint,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketTypeReply) Reset() {
	*x = UpdateTicketTypeReply{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketTypeReply) ProtoMessage() {}

func (x *UpdateTicketTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketTypeReply.ProtoReflect.Descriptor instead.
func (*UpdateTicketTypeReply) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTicketTypeReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTicketTypeReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTicketTypeReply) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTicketTypeReply) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateTicketTypeReply) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *UpdateTicketTypeReply) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdateTicketTypeReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type DeleteTicketTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketTypeRequest) Reset() {
	*x = DeleteTicketTypeRequest{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketTypeRequest) ProtoMessage() {}

func (x *DeleteTicketTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteTicketTypeRequest) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTicketTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTicketTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketTypeReply) Reset() {
	*x = DeleteTicketTypeReply{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketTypeReply) ProtoMessage() {}

func (x *DeleteTicketTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketTypeReply.ProtoReflect.Descriptor instead.
func (*DeleteTicketTypeReply) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{5}
}

type GetTicketTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketTypeRequest) Reset() {
	*x = GetTicketTypeRequest{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketTypeRequest) ProtoMessage() {}

func (x *GetTicketTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTicketTypeRequest) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{6}
}

func (x *GetTicketTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTicketTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,5,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	EventId       int64                  `protobuf:"varint,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketTypeReply) Reset() {
	*x = GetTicketTypeReply{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketTypeReply) ProtoMessage() {}

func (x *GetTicketTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketTypeReply.ProtoReflect.Descriptor instead.
func (*GetTicketTypeReply) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{7}
}

func (x *GetTicketTypeReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTicketTypeReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTicketTypeReply) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetTicketTypeReply) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetTicketTypeReply) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *GetTicketTypeReply) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *GetTicketTypeReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type TicketTypeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,5,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	EventId       int64                  `protobuf:"varint,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketTypeData) Reset() {
	*x = TicketTypeData{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketTypeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketTypeData) ProtoMessage() {}

func (x *TicketTypeData) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketTypeData.ProtoReflect.Descriptor instead.
func (*TicketTypeData) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{8}
}

func (x *TicketTypeData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketTypeData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketTypeData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketTypeData) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *TicketTypeData) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *TicketTypeData) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *TicketTypeData) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type ListTicketTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketTypeRequest) Reset() {
	*x = ListTicketTypeRequest{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketTypeRequest) ProtoMessage() {}

func (x *ListTicketTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketTypeRequest.ProtoReflect.Descriptor instead.
func (*ListTicketTypeRequest) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{9}
}

func (x *ListTicketTypeRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTicketTypeRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListTicketTypeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TicketTypeData      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketTypeReply) Reset() {
	*x = ListTicketTypeReply{}
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketTypeReply) ProtoMessage() {}

func (x *ListTicketTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_v1_ticket_type_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketTypeReply.ProtoReflect.Descriptor instead.
func (*ListTicketTypeReply) Descriptor() ([]byte, []int) {
	return file_ticket_type_v1_ticket_type_proto_rawDescGZIP(), []int{10}
}

func (x *ListTicketTypeReply) GetList() []*TicketTypeData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTicketTypeReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_ticket_type_v1_ticket_type_proto protoreflect.FileDescriptor

const file_ticket_type_v1_ticket_type_proto_rawDesc = "" +
	"\n" +
	" ticket_type/v1/ticket_type.proto\x12\x12api.ticket_type.v1\"\xb5\x01\n" +
	"\x17CreateTicketTypeRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12 \n" +
	"\fmax_per_user\x18\x05 \x01(\x05R\n" +
	"maxPerUser\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\"\xc3\x01\n" +
	"\x15CreateTicketTypeReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12 \n" +
	"\fmax_per_user\x18\x05 \x01(\x05R\n" +
	"maxPerUser\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x19\n" +
	"\bevent_id\x18\a \x01(\x03R\aeventId\"\xc5\x01\n" +
	"\x17UpdateTicketTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12 \n" +
	"\fmax_per_user\x18\x05 \x01(\x05R\n" +
	"maxPerUser\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x19\n" +
	"\bevent_id\x18\a \x01(\x03R\aeventId\"\xc3\x01\n" +
	"\x15UpdateTicketTypeReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12 \n" +
	"\fmax_per_user\x18\x05 \x01(\x05R\n" +
	"maxPerUser\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x19\n" +
	"\bevent_id\x18\a \x01(\x03R\aeventId\")\n" +
	"\x17DeleteTicketTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15DeleteTicketTypeReply\"&\n" +
	"\x14GetTicketTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc0\x01\n" +
	"\x12GetTicketTypeReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12 \n" +
	"\fmax_per_user\x18\x05 \x01(\x05R\n" +
	"maxPerUser\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x19\n" +
	"\bevent_id\x18\a \x01(\x03R\aeventId\"\xbc\x01\n" +
	"\x0eTicketTypeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12 \n" +
	"\fmax_per_user\x18\x05 \x01(\x05R\n" +
	"maxPerUser\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x19\n" +
	"\bevent_id\x18\a \x01(\x03R\aeventId\"?\n" +
	"\x15ListTicketTypeRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"c\n" +
	"\x13ListTicketTypeReply\x126\n" +
	"\x04list\x18\x01 \x03(\v2\".api.ticket_type.v1.TicketTypeDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x99\x04\n" +
	"\n" +
	"TicketType\x12j\n" +
	"\x10CreateTicketType\x12+.api.ticket_type.v1.CreateTicketTypeRequest\x1a).api.ticket_type.v1.CreateTicketTypeReply\x12j\n" +
	"\x10UpdateTicketType\x12+.api.ticket_type.v1.UpdateTicketTypeRequest\x1a).api.ticket_type.v1.UpdateTicketTypeReply\x12j\n" +
	"\x10DeleteTicketType\x12+.api.ticket_type.v1.DeleteTicketTypeRequest\x1a).api.ticket_type.v1.DeleteTicketTypeReply\x12a\n" +
	"\rGetTicketType\x12(.api.ticket_type.v1.GetTicketTypeRequest\x1a&.api.ticket_type.v1.GetTicketTypeReply\x12d\n" +
	"\x0eListTicketType\x12).api.ticket_type.v1.ListTicketTypeRequest\x1a'.api.ticket_type.v1.ListTicketTypeReplyB3\n" +
	"\x12api.ticket_type.v1P\x01Z\x1badmin/api/ticket_type/v1;v1b\x06proto3"

var (
	file_ticket_type_v1_ticket_type_proto_rawDescOnce sync.Once
	file_ticket_type_v1_ticket_type_proto_rawDescData []byte
)

func file_ticket_type_v1_ticket_type_proto_rawDescGZIP() []byte {
	file_ticket_type_v1_ticket_type_proto_rawDescOnce.Do(func() {
		file_ticket_type_v1_ticket_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_type_v1_ticket_type_proto_rawDesc), len(file_ticket_type_v1_ticket_type_proto_rawDesc)))
	})
	return file_ticket_type_v1_ticket_type_proto_rawDescData
}

var file_ticket_type_v1_ticket_type_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ticket_type_v1_ticket_type_proto_goTypes = []any{
	(*CreateTicketTypeRequest)(nil), // 0: api.ticket_type.v1.CreateTicketTypeRequest
	(*CreateTicketTypeReply)(nil),   // 1: api.ticket_type.v1.CreateTicketTypeReply
	(*UpdateTicketTypeRequest)(nil), // 2: api.ticket_type.v1.UpdateTicketTypeRequest
	(*UpdateTicketTypeReply)(nil),   // 3: api.ticket_type.v1.UpdateTicketTypeReply
	(*DeleteTicketTypeRequest)(nil), // 4: api.ticket_type.v1.DeleteTicketTypeRequest
	(*DeleteTicketTypeReply)(nil),   // 5: api.ticket_type.v1.DeleteTicketTypeReply
	(*GetTicketTypeRequest)(nil),    // 6: api.ticket_type.v1.GetTicketTypeRequest
	(*GetTicketTypeReply)(nil),      // 7: api.ticket_type.v1.GetTicketTypeReply
	(*TicketTypeData)(nil),          // 8: api.ticket_type.v1.TicketTypeData
	(*ListTicketTypeRequest)(nil),   // 9: api.ticket_type.v1.ListTicketTypeRequest
	(*ListTicketTypeReply)(nil),     // 10: api.ticket_type.v1.ListTicketTypeReply
}
var file_ticket_type_v1_ticket_type_proto_depIdxs = []int32{
	8,  // 0: api.ticket_type.v1.ListTicketTypeReply.list:type_name -> api.ticket_type.v1.TicketTypeData
	0,  // 1: api.ticket_type.v1.TicketType.CreateTicketType:input_type -> api.ticket_type.v1.CreateTicketTypeRequest
	2,  // 2: api.ticket_type.v1.TicketType.UpdateTicketType:input_type -> api.ticket_type.v1.UpdateTicketTypeRequest
	4,  // 3: api.ticket_type.v1.TicketType.DeleteTicketType:input_type -> api.ticket_type.v1.DeleteTicketTypeRequest
	6,  // 4: api.ticket_type.v1.TicketType.GetTicketType:input_type -> api.ticket_type.v1.GetTicketTypeRequest
	9,  // 5: api.ticket_type.v1.TicketType.ListTicketType:input_type -> api.ticket_type.v1.ListTicketTypeRequest
	1,  // 6: api.ticket_type.v1.TicketType.CreateTicketType:output_type -> api.ticket_type.v1.CreateTicketTypeReply
	3,  // 7: api.ticket_type.v1.TicketType.UpdateTicketType:output_type -> api.ticket_type.v1.UpdateTicketTypeReply
	5,  // 8: api.ticket_type.v1.TicketType.DeleteTicketType:output_type -> api.ticket_type.v1.DeleteTicketTypeReply
	7,  // 9: api.ticket_type.v1.TicketType.GetTicketType:output_type -> api.ticket_type.v1.GetTicketTypeReply
	10, // 10: api.ticket_type.v1.TicketType.ListTicketType:output_type -> api.ticket_type.v1.ListTicketTypeReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_ticket_type_v1_ticket_type_proto_init() }
func file_ticket_type_v1_ticket_type_proto_init() {
	if File_ticket_type_v1_ticket_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_type_v1_ticket_type_proto_rawDesc), len(file_ticket_type_v1_ticket_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_type_v1_ticket_type_proto_goTypes,
		DependencyIndexes: file_ticket_type_v1_ticket_type_proto_depIdxs,
		MessageInfos:      file_ticket_type_v1_ticket_type_proto_msgTypes,
	}.Build()
	File_ticket_type_v1_ticket_type_proto = out.File
	file_ticket_type_v1_ticket_type_proto_goTypes = nil
	file_ticket_type_v1_ticket_type_proto_depIdxs = nil
}
