// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ticket_type/v1/ticket_type.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TicketType_CreateTicketType_FullMethodName = "/api.ticket_type.v1.TicketType/CreateTicketType"
	TicketType_UpdateTicketType_FullMethodName = "/api.ticket_type.v1.TicketType/UpdateTicketType"
	TicketType_DeleteTicketType_FullMethodName = "/api.ticket_type.v1.TicketType/DeleteTicketType"
	TicketType_GetTicketType_FullMethodName    = "/api.ticket_type.v1.TicketType/GetTicketType"
	TicketType_ListTicketType_FullMethodName   = "/api.ticket_type.v1.TicketType/ListTicketType"
)

// TicketTypeClient is the client API for TicketType service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketTypeClient interface {
	CreateTicketType(ctx context.Context, in *CreateTicketTypeRequest, opts ...grpc.CallOption) (*CreateTicketTypeReply, error)
	UpdateTicketType(ctx context.Context, in *UpdateTicketTypeRequest, opts ...grpc.CallOption) (*UpdateTicketTypeReply, error)
	DeleteTicketType(ctx context.Context, in *DeleteTicketTypeRequest, opts ...grpc.CallOption) (*DeleteTicketTypeReply, error)
	GetTicketType(ctx context.Context, in *GetTicketTypeRequest, opts ...grpc.CallOption) (*GetTicketTypeReply, error)
	ListTicketType(ctx context.Context, in *ListTicketTypeRequest, opts ...grpc.CallOption) (*ListTicketTypeReply, error)
}

type ticketTypeClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketTypeClient(cc grpc.ClientConnInterface) TicketTypeClient {
	return &ticketTypeClient{cc}
}

func (c *ticketTypeClient) CreateTicketType(ctx context.Context, in *CreateTicketTypeRequest, opts ...grpc.CallOption) (*CreateTicketTypeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTicketTypeReply)
	err := c.cc.Invoke(ctx, TicketType_CreateTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketTypeClient) UpdateTicketType(ctx context.Context, in *UpdateTicketTypeRequest, opts ...grpc.CallOption) (*UpdateTicketTypeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTicketTypeReply)
	err := c.cc.Invoke(ctx, TicketType_UpdateTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketTypeClient) DeleteTicketType(ctx context.Context, in *DeleteTicketTypeRequest, opts ...grpc.CallOption) (*DeleteTicketTypeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTicketTypeReply)
	err := c.cc.Invoke(ctx, TicketType_DeleteTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketTypeClient) GetTicketType(ctx context.Context, in *GetTicketTypeRequest, opts ...grpc.CallOption) (*GetTicketTypeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketTypeReply)
	err := c.cc.Invoke(ctx, TicketType_GetTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketTypeClient) ListTicketType(ctx context.Context, in *ListTicketTypeRequest, opts ...grpc.CallOption) (*ListTicketTypeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTicketTypeReply)
	err := c.cc.Invoke(ctx, TicketType_ListTicketType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketTypeServer is the server API for TicketType service.
// All implementations must embed UnimplementedTicketTypeServer
// for forward compatibility.
type TicketTypeServer interface {
	CreateTicketType(context.Context, *CreateTicketTypeRequest) (*CreateTicketTypeReply, error)
	UpdateTicketType(context.Context, *UpdateTicketTypeRequest) (*UpdateTicketTypeReply, error)
	DeleteTicketType(context.Context, *DeleteTicketTypeRequest) (*DeleteTicketTypeReply, error)
	GetTicketType(context.Context, *GetTicketTypeRequest) (*GetTicketTypeReply, error)
	ListTicketType(context.Context, *ListTicketTypeRequest) (*ListTicketTypeReply, error)
	mustEmbedUnimplementedTicketTypeServer()
}

// UnimplementedTicketTypeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketTypeServer struct{}

func (UnimplementedTicketTypeServer) CreateTicketType(context.Context, *CreateTicketTypeRequest) (*CreateTicketTypeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicketType not implemented")
}
func (UnimplementedTicketTypeServer) UpdateTicketType(context.Context, *UpdateTicketTypeRequest) (*UpdateTicketTypeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicketType not implemented")
}
func (UnimplementedTicketTypeServer) DeleteTicketType(context.Context, *DeleteTicketTypeRequest) (*DeleteTicketTypeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTicketType not implemented")
}
func (UnimplementedTicketTypeServer) GetTicketType(context.Context, *GetTicketTypeRequest) (*GetTicketTypeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicketType not implemented")
}
func (UnimplementedTicketTypeServer) ListTicketType(context.Context, *ListTicketTypeRequest) (*ListTicketTypeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTicketType not implemented")
}
func (UnimplementedTicketTypeServer) mustEmbedUnimplementedTicketTypeServer() {}
func (UnimplementedTicketTypeServer) testEmbeddedByValue()                    {}

// UnsafeTicketTypeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketTypeServer will
// result in compilation errors.
type UnsafeTicketTypeServer interface {
	mustEmbedUnimplementedTicketTypeServer()
}

func RegisterTicketTypeServer(s grpc.ServiceRegistrar, srv TicketTypeServer) {
	// If the following call panics, it indicates UnimplementedTicketTypeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketType_ServiceDesc, srv)
}

func _TicketType_CreateTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketTypeServer).CreateTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketType_CreateTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketTypeServer).CreateTicketType(ctx, req.(*CreateTicketTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketType_UpdateTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketTypeServer).UpdateTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketType_UpdateTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketTypeServer).UpdateTicketType(ctx, req.(*UpdateTicketTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketType_DeleteTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTicketTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketTypeServer).DeleteTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketType_DeleteTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketTypeServer).DeleteTicketType(ctx, req.(*DeleteTicketTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketType_GetTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketTypeServer).GetTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketType_GetTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketTypeServer).GetTicketType(ctx, req.(*GetTicketTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketType_ListTicketType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketTypeServer).ListTicketType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketType_ListTicketType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketTypeServer).ListTicketType(ctx, req.(*ListTicketTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketType_ServiceDesc is the grpc.ServiceDesc for TicketType service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketType_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ticket_type.v1.TicketType",
	HandlerType: (*TicketTypeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTicketType",
			Handler:    _TicketType_CreateTicketType_Handler,
		},
		{
			MethodName: "UpdateTicketType",
			Handler:    _TicketType_UpdateTicketType_Handler,
		},
		{
			MethodName: "DeleteTicketType",
			Handler:    _TicketType_DeleteTicketType_Handler,
		},
		{
			MethodName: "GetTicketType",
			Handler:    _TicketType_GetTicketType_Handler,
		},
		{
			MethodName: "ListTicketType",
			Handler:    _TicketType_ListTicketType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticket_type/v1/ticket_type.proto",
}
