// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: seckill/v1/seckill.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSeckillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ShowId        int64                  `protobuf:"varint,2,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	TicketTypeId  int64                  `protobuf:"varint,3,opt,name=ticket_type_id,json=ticketTypeId,proto3" json:"ticket_type_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeckillRequest) Reset() {
	*x = CreateSeckillRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeckillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeckillRequest) ProtoMessage() {}

func (x *CreateSeckillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeckillRequest.ProtoReflect.Descriptor instead.
func (*CreateSeckillRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSeckillRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateSeckillRequest) GetShowId() int64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *CreateSeckillRequest) GetTicketTypeId() int64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *CreateSeckillRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateSeckillReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PurchaseToken string                 `protobuf:"bytes,3,opt,name=purchase_token,json=purchaseToken,proto3" json:"purchase_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeckillReply) Reset() {
	*x = CreateSeckillReply{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeckillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeckillReply) ProtoMessage() {}

func (x *CreateSeckillReply) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeckillReply.ProtoReflect.Descriptor instead.
func (*CreateSeckillReply) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSeckillReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSeckillReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateSeckillReply) GetPurchaseToken() string {
	if x != nil {
		return x.PurchaseToken
	}
	return ""
}

type InitSeckillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSeckillRequest) Reset() {
	*x = InitSeckillRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSeckillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSeckillRequest) ProtoMessage() {}

func (x *InitSeckillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSeckillRequest.ProtoReflect.Descriptor instead.
func (*InitSeckillRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *InitSeckillRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *InitSeckillRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InitSeckillRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type InitSeckillReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSeckillReply) Reset() {
	*x = InitSeckillReply{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSeckillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSeckillReply) ProtoMessage() {}

func (x *InitSeckillReply) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSeckillReply.ProtoReflect.Descriptor instead.
func (*InitSeckillReply) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{3}
}

type GetSeckillResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 同样来自 JWT
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketTypeId  int64                  `protobuf:"varint,3,opt,name=ticket_type_id,json=ticketTypeId,proto3" json:"ticket_type_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // CreateSeckillReply 返回的关联 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillResultRequest) Reset() {
	*x = GetSeckillResultRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillResultRequest) ProtoMessage() {}

func (x *GetSeckillResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillResultRequest.ProtoReflect.Descriptor instead.
func (*GetSeckillResultRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{4}
}

func (x *GetSeckillResultRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSeckillResultRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *GetSeckillResultRequest) GetTicketTypeId() int64 {
	if x != nil {
		return x.TicketTypeId
	}
	return 0
}

func (x *GetSeckillResultRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetSeckillResultReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // processing / success / failed
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 原样回显，方便客户端匹配
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillResultReply) Reset() {
	*x = GetSeckillResultReply{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillResultReply) ProtoMessage() {}

func (x *GetSeckillResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillResultReply.ProtoReflect.Descriptor instead.
func (*GetSeckillResultReply) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{5}
}

func (x *GetSeckillResultReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetSeckillResultReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSeckillResultReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetSeckillResultReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_seckill_v1_seckill_proto protoreflect.FileDescriptor

const file_seckill_v1_seckill_proto_rawDesc = "" +
	"\n" +
	"\x18seckill/v1/seckill.proto\x12\x0eapi.seckill.v1\"\x8c\x01\n" +
	"\x14CreateSeckillRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x17\n" +
	"\ashow_id\x18\x02 \x01(\x03R\x06showId\x12$\n" +
	"\x0eticket_type_id\x18\x03 \x01(\x03R\fticketTypeId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"m\n" +
	"\x12CreateSeckillReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0epurchase_token\x18\x03 \x01(\tR\rpurchaseToken\"j\n" +
	"\x12InitSeckillRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x03R\x05stock\"\x12\n" +
	"\x10InitSeckillReply\"\x91\x01\n" +
	"\x17GetSeckillResultRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12$\n" +
	"\x0eticket_type_id\x18\x03 \x01(\x03R\fticketTypeId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x82\x01\n" +
	"\x15GetSeckillResultReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\x9d\x02\n" +
	"\aSeckill\x12Y\n" +
	"\rCreateSeckill\x12$.api.seckill.v1.CreateSeckillRequest\x1a\".api.seckill.v1.CreateSeckillReply\x12S\n" +
	"\vInitSeckill\x12\".api.seckill.v1.InitSeckillRequest\x1a .api.seckill.v1.InitSeckillReply\x12b\n" +
	"\x10GetSeckillResult\x12'.api.seckill.v1.GetSeckillResultRequest\x1a%.api.seckill.v1.GetSeckillResultReplyB-\n" +
	"\x0eapi.seckill.v1P\x01Z\x19seckill/api/seckill/v1;v1b\x06proto3"

var (
	file_seckill_v1_seckill_proto_rawDescOnce sync.Once
	file_seckill_v1_seckill_proto_rawDescData []byte
)

func file_seckill_v1_seckill_proto_rawDescGZIP() []byte {
	file_seckill_v1_seckill_proto_rawDescOnce.Do(func() {
		file_seckill_v1_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seckill_v1_seckill_proto_rawDesc), len(file_seckill_v1_seckill_proto_rawDesc)))
	})
	return file_seckill_v1_seckill_proto_rawDescData
}

var file_seckill_v1_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_seckill_v1_seckill_proto_goTypes = []any{
	(*CreateSeckillRequest)(nil),    // 0: api.seckill.v1.CreateSeckillRequest
	(*CreateSeckillReply)(nil),      // 1: api.seckill.v1.CreateSeckillReply
	(*InitSeckillRequest)(nil),      // 2: api.seckill.v1.InitSeckillRequest
	(*InitSeckillReply)(nil),        // 3: api.seckill.v1.InitSeckillReply
	(*GetSeckillResultRequest)(nil), // 4: api.seckill.v1.GetSeckillResultRequest
	(*GetSeckillResultReply)(nil),   // 5: api.seckill.v1.GetSeckillResultReply
}
var file_seckill_v1_seckill_proto_depIdxs = []int32{
	0, // 0: api.seckill.v1.Seckill.CreateSeckill:input_type -> api.seckill.v1.CreateSeckillRequest
	2, // 1: api.seckill.v1.Seckill.InitSeckill:input_type -> api.seckill.v1.InitSeckillRequest
	4, // 2: api.seckill.v1.Seckill.GetSeckillResult:input_type -> api.seckill.v1.GetSeckillResultRequest
	1, // 3: api.seckill.v1.Seckill.CreateSeckill:output_type -> api.seckill.v1.CreateSeckillReply
	3, // 4: api.seckill.v1.Seckill.InitSeckill:output_type -> api.seckill.v1.InitSeckillReply
	5, // 5: api.seckill.v1.Seckill.GetSeckillResult:output_type -> api.seckill.v1.GetSeckillResultReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seckill_v1_seckill_proto_init() }
func file_seckill_v1_seckill_proto_init() {
	if File_seckill_v1_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seckill_v1_seckill_proto_rawDesc), len(file_seckill_v1_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seckill_v1_seckill_proto_goTypes,
		DependencyIndexes: file_seckill_v1_seckill_proto_depIdxs,
		MessageInfos:      file_seckill_v1_seckill_proto_msgTypes,
	}.Build()
	File_seckill_v1_seckill_proto = out.File
	file_seckill_v1_seckill_proto_goTypes = nil
	file_seckill_v1_seckill_proto_depIdxs = nil
}
