// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: seckill/v1/seckill.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Seckill_CreateSeckill_FullMethodName    = "/api.seckill.v1.Seckill/CreateSeckill"
	Seckill_InitSeckill_FullMethodName      = "/api.seckill.v1.Seckill/InitSeckill"
	Seckill_GetSeckillResult_FullMethodName = "/api.seckill.v1.Seckill/GetSeckillResult"
)

// SeckillClient is the client API for Seckill service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeckillClient interface {
	CreateSeckill(ctx context.Context, in *CreateSeckillRequest, opts ...grpc.CallOption) (*CreateSeckillReply, error)
	// 预热活动
	InitSeckill(ctx context.Context, in *InitSeckillRequest, opts ...grpc.CallOption) (*InitSeckillReply, error)
	// 轮询兜底：WS 推送丢失/超时时，客户端凭关联 ID 主动查询结果
	GetSeckillResult(ctx context.Context, in *GetSeckillResultRequest, opts ...grpc.CallOption) (*GetSeckillResultReply, error)
}

type seckillClient struct {
	cc grpc.ClientConnInterface
}

func NewSeckillClient(cc grpc.ClientConnInterface) SeckillClient {
	return &seckillClient{cc}
}

func (c *seckillClient) CreateSeckill(ctx context.Context, in *CreateSeckillRequest, opts ...grpc.CallOption) (*CreateSeckillReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSeckillReply)
	err := c.cc.Invoke(ctx, Seckill_CreateSeckill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillClient) InitSeckill(ctx context.Context, in *InitSeckillRequest, opts ...grpc.CallOption) (*InitSeckillReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitSeckillReply)
	err := c.cc.Invoke(ctx, Seckill_InitSeckill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillClient) GetSeckillResult(ctx context.Context, in *GetSeckillResultRequest, opts ...grpc.CallOption) (*GetSeckillResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeckillResultReply)
	err := c.cc.Invoke(ctx, Seckill_GetSeckillResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeckillServer is the server API for Seckill service.
// All implementations must embed UnimplementedSeckillServer
// for forward compatibility.
type SeckillServer interface {
	CreateSeckill(context.Context, *CreateSeckillRequest) (*CreateSeckillReply, error)
	// 预热活动
	InitSeckill(context.Context, *InitSeckillRequest) (*InitSeckillReply, error)
	// 轮询兜底：WS 推送丢失/超时时，客户端凭关联 ID 主动查询结果
	GetSeckillResult(context.Context, *GetSeckillResultRequest) (*GetSeckillResultReply, error)
	mustEmbedUnimplementedSeckillServer()
}

// UnimplementedSeckillServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeckillServer struct{}

func (UnimplementedSeckillServer) CreateSeckill(context.Context, *CreateSeckillRequest) (*CreateSeckillReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeckill not implemented")
}
func (UnimplementedSeckillServer) InitSeckill(context.Context, *InitSeckillRequest) (*InitSeckillReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InitSeckill not implemented")
}
func (UnimplementedSeckillServer) GetSeckillResult(context.Context, *GetSeckillResultRequest) (*GetSeckillResultReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeckillResult not implemented")
}
func (UnimplementedSeckillServer) mustEmbedUnimplementedSeckillServer() {}
func (UnimplementedSeckillServer) testEmbeddedByValue()                 {}

// UnsafeSeckillServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeckillServer will
// result in compilation errors.
type UnsafeSeckillServer interface {
	mustEmbedUnimplementedSeckillServer()
}

func RegisterSeckillServer(s grpc.ServiceRegistrar, srv SeckillServer) {
	// If the following call panics, it indicates UnimplementedSeckillServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Seckill_ServiceDesc, srv)
}

func _Seckill_CreateSeckill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSeckillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).CreateSeckill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_CreateSeckill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).CreateSeckill(ctx, req.(*CreateSeckillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seckill_InitSeckill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitSeckillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).InitSeckill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_InitSeckill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).InitSeckill(ctx, req.(*InitSeckillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seckill_GetSeckillResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeckillResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServer).GetSeckillResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seckill_GetSeckillResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServer).GetSeckillResult(ctx, req.(*GetSeckillResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Seckill_ServiceDesc is the grpc.ServiceDesc for Seckill service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Seckill_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.seckill.v1.Seckill",
	HandlerType: (*SeckillServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSeckill",
			Handler:    _Seckill_CreateSeckill_Handler,
		},
		{
			MethodName: "InitSeckill",
			Handler:    _Seckill_InitSeckill_Handler,
		},
		{
			MethodName: "GetSeckillResult",
			Handler:    _Seckill_GetSeckillResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seckill/v1/seckill.proto",
}
