// Code generated by hertz generator.

package show

import (
	"getway/mvw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return mvw.AuthMiddleware()
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listshowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _showsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getshowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _geteventshowMw() []app.HandlerFunc {
	// your code...
	return nil
}
