// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"market/internal/biz"
	"market/internal/data"
	"market/internal/server"
	"market/internal/service"
	"sale/pkg/conf"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	listingRepo := data.NewListingRepo(dataData, logger)
	catalogRepo := data.NewCatalogRepo(dataData, logger)
	marketplaceUseCase := biz.NewMarketplaceUseCase(listingRepo, catalogRepo, logger)
	transferRepo := data.NewTransferRepo(dataData, logger)
	transferUseCase := biz.NewTransferUseCase(transferRepo, logger)
	marketplaceService := service.NewMarketplaceService(marketplaceUseCase, transferUseCase)
	grpcServer := server.NewGRPCServer(confServer, logger, marketplaceService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
