// Code generated by hertz generator.

package event

import (
	eventv1 "activity/api/event/v1"
	"context"

	"getway/biz/client"
	"getway/biz/handler/response"
	event "getway/biz/model/event"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// GetEvent .
// @router /api/events/:id [GET]
func GetEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.GetEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	res, err := client.GetEvent().GetEvent(ctx, &eventv1.GetEventRequest{
		Id: req.GetId(),
	})
	if err != nil {
		hlog.Error(err.Error())
		response.HandleBussinessFail(c, err.Error())
		return
	}
	resp := &event.GetEventResp{
		Title:       res.GetTitle(),
		Description: res.GetDescription(),
		Location:    res.GetLocation(),
		CoverImage:  res.GetCoverImage(),
		StartTime:   res.GetStartTime(),
		EndTime:     res.GetEndTime(),
		SoldCount:   res.GetSoldCount(),
	}
	response.HandleSuccess(c, resp)
}

// ListEvent .
// @router /api/events [GET]
func ListEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.ListEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	res, err := client.GetEvent().ListEvent(ctx, &eventv1.ListEventRequest{
		Page: req.GetPage(),
		Size: req.GetSize(),
	})
	if err != nil {
		hlog.Error(err.Error())
		response.HandleBussinessFail(c, err.Error())
		return
	}
	list := make([]*event.EventData, 0, len(res.GetList()))
	for _, it := range res.GetList() {
		list = append(list, &event.EventData{
			Id:          it.GetId(),
			Title:       it.GetTitle(),
			Description: it.GetDescription(),
			Location:    it.GetLocation(),
			CoverImage:  it.GetCoverImage(),
			StartTime:   it.GetStartTime(),
			EndTime:     it.GetEndTime(),
			Status:      it.GetStatus(),
			SoldCount:   it.GetSoldCount(),
		})
	}
	resp := &event.ListEventResp{
		List:  list,
		Total: res.GetTotal(),
	}
	response.HandleSuccess(c, resp)
}

// DeleteEvent .
// @router /api/events/:id [DELETE]
func DeleteEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.DeleteEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	_, err = client.GetEvent().DeleteEvent(ctx, &eventv1.DeleteEventRequest{
		Id: req.GetId(),
	})
	if err != nil {
		hlog.Error(err.Error())
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &event.DeleteEventResp{})
}

// GetEventStock .
// @router /api/events/:id/stock [GET]
func GetEventStock(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.GetEventStockReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	res, err := client.GetEvent().GetEventStock(ctx, &eventv1.GetEventStockRequest{
		Id: req.GetId(),
	})
	if err != nil {
		hlog.Error(err.Error())
		response.HandleBussinessFail(c, err.Error())
		return
	}
	stocks := make([]*event.TicketTypeStock, 0, len(res.GetStocks()))
	for _, it := range res.GetStocks() {
		stocks = append(stocks, &event.TicketTypeStock{
			TicketTypeId: it.GetTicketTypeId(),
			Stock:        it.GetStock(),
		})
	}
	response.HandleSuccess(c, &event.GetEventStockResp{Stocks: stocks})
}
