// Code generated by hertz generator.

package admin

import (
	"getway/mvw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return mvw.AuthMiddleware()
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createeventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateeventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _endeventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publisheventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createshowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtickettypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unpublisheventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _showsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _id0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteshowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishshowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unpublishshowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateshowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ticket_typesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetickettypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetickettypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _promoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createpromocodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepromocodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdashboardstatsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsalestrendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettickettypestatsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _funnelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconversionfunnelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transferMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpendingtransfersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _id1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _approvetransferMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rejecttransferMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserroleMw() []app.HandlerFunc {
	// your code...
	return nil
}
