// idl/ticket_type/ticket_type.proto
// 通用 /api 前缀的 HTTP 契约：getway 接收 HTTP 请求后转发给 activity 服务的
// TicketType gRPC 接口（activity/api/ticket_type/v1/ticket_type.proto）。
// 这里只收编 admin.proto 未对接的 RPC：GetTicketType / ListTicketType。
// 消息字段与上游 proto 一比一对齐，便于 handler 直接透传。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: ticket_type.proto

package ticket_type

import (
	_ "getway/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTicketTypeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
}

func (x *GetTicketTypeReq) Reset() {
	*x = GetTicketTypeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTicketTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketTypeReq) ProtoMessage() {}

func (x *GetTicketTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketTypeReq.ProtoReflect.Descriptor instead.
func (*GetTicketTypeReq) Descriptor() ([]byte, []int) {
	return file_ticket_type_proto_rawDescGZIP(), []int{0}
}

func (x *GetTicketTypeReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTicketTypeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64   `protobuf:"varint,1,opt,name=id,proto3" form:"id" json:"id,omitempty" query:"id"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
	Price      float32 `protobuf:"fixed32,3,opt,name=price,proto3" form:"price" json:"price,omitempty" query:"price"`
	Stock      int32   `protobuf:"varint,4,opt,name=stock,proto3" form:"stock" json:"stock,omitempty" query:"stock"`
	MaxPerUser int32   `protobuf:"varint,5,opt,name=max_per_user,json=maxPerUser,proto3" form:"max_per_user" json:"max_per_user,omitempty" query:"max_per_user"`
	SortOrder  int32   `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" form:"sort_order" json:"sort_order,omitempty" query:"sort_order"`
	EventId    int64   `protobuf:"varint,7,opt,name=event_id,json=eventId,proto3" form:"event_id" json:"event_id,omitempty" query:"event_id"`
}

func (x *GetTicketTypeResp) Reset() {
	*x = GetTicketTypeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTicketTypeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketTypeResp) ProtoMessage() {}

func (x *GetTicketTypeResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketTypeResp.ProtoReflect.Descriptor instead.
func (*GetTicketTypeResp) Descriptor() ([]byte, []int) {
	return file_ticket_type_proto_rawDescGZIP(), []int{1}
}

func (x *GetTicketTypeResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTicketTypeResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTicketTypeResp) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetTicketTypeResp) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetTicketTypeResp) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *GetTicketTypeResp) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *GetTicketTypeResp) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type ListTicketTypeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" query:"page"`
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty" query:"size"`
}

func (x *ListTicketTypeReq) Reset() {
	*x = ListTicketTypeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTicketTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketTypeReq) ProtoMessage() {}

func (x *ListTicketTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketTypeReq.ProtoReflect.Descriptor instead.
func (*ListTicketTypeReq) Descriptor() ([]byte, []int) {
	return file_ticket_type_proto_rawDescGZIP(), []int{2}
}

func (x *ListTicketTypeReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTicketTypeReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type TicketTypeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64   `protobuf:"varint,1,opt,name=id,proto3" form:"id" json:"id,omitempty" query:"id"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
	Price      float32 `protobuf:"fixed32,3,opt,name=price,proto3" form:"price" json:"price,omitempty" query:"price"`
	Stock      int32   `protobuf:"varint,4,opt,name=stock,proto3" form:"stock" json:"stock,omitempty" query:"stock"`
	MaxPerUser int32   `protobuf:"varint,5,opt,name=max_per_user,json=maxPerUser,proto3" form:"max_per_user" json:"max_per_user,omitempty" query:"max_per_user"`
	SortOrder  int32   `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" form:"sort_order" json:"sort_order,omitempty" query:"sort_order"`
	EventId    int64   `protobuf:"varint,7,opt,name=event_id,json=eventId,proto3" form:"event_id" json:"event_id,omitempty" query:"event_id"`
}

func (x *TicketTypeData) Reset() {
	*x = TicketTypeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketTypeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketTypeData) ProtoMessage() {}

func (x *TicketTypeData) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketTypeData.ProtoReflect.Descriptor instead.
func (*TicketTypeData) Descriptor() ([]byte, []int) {
	return file_ticket_type_proto_rawDescGZIP(), []int{3}
}

func (x *TicketTypeData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketTypeData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketTypeData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketTypeData) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *TicketTypeData) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *TicketTypeData) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *TicketTypeData) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type ListTicketTypeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*TicketTypeData `protobuf:"bytes,1,rep,name=list,proto3" form:"list" json:"list,omitempty" query:"list"`
	Total int64             `protobuf:"varint,2,opt,name=total,proto3" form:"total" json:"total,omitempty" query:"total"`
}

func (x *ListTicketTypeResp) Reset() {
	*x = ListTicketTypeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTicketTypeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketTypeResp) ProtoMessage() {}

func (x *ListTicketTypeResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketTypeResp.ProtoReflect.Descriptor instead.
func (*ListTicketTypeResp) Descriptor() ([]byte, []int) {
	return file_ticket_type_proto_rawDescGZIP(), []int{4}
}

func (x *ListTicketTypeResp) GetList() []*TicketTypeData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTicketTypeResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_ticket_type_proto protoreflect.FileDescriptor

var file_ticket_type_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x1a, 0x09, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x06, 0xd2, 0xbb, 0x18, 0x02, 0x69, 0x64, 0x52, 0x02,
	0x69, 0x64, 0x22, 0xbf, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f,
	0x70, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x6d, 0x61, 0x78, 0x50, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f,
	0x72, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x08, 0xb2, 0xbb, 0x18, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x08, 0xb2, 0xbb, 0x18, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x0e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f,
	0x70, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x6d, 0x61, 0x78, 0x50, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f,
	0x72, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x65, 0x74, 0x77, 0x61,
	0x79, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0xd5, 0x01, 0x0a,
	0x12, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x5f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x2e, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19,
	0x2e, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x19, 0xca, 0xc1, 0x18, 0x15, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x3a, 0x69, 0x64, 0x12, 0x5e, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x1a, 0x2e, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x15, 0xca,
	0xc1, 0x18, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2d, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2f, 0x62,
	0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ticket_type_proto_rawDescOnce sync.Once
	file_ticket_type_proto_rawDescData = file_ticket_type_proto_rawDesc
)

func file_ticket_type_proto_rawDescGZIP() []byte {
	file_ticket_type_proto_rawDescOnce.Do(func() {
		file_ticket_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_ticket_type_proto_rawDescData)
	})
	return file_ticket_type_proto_rawDescData
}

var file_ticket_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ticket_type_proto_goTypes = []interface{}{
	(*GetTicketTypeReq)(nil),   // 0: getway.GetTicketTypeReq
	(*GetTicketTypeResp)(nil),  // 1: getway.GetTicketTypeResp
	(*ListTicketTypeReq)(nil),  // 2: getway.ListTicketTypeReq
	(*TicketTypeData)(nil),     // 3: getway.TicketTypeData
	(*ListTicketTypeResp)(nil), // 4: getway.ListTicketTypeResp
}
var file_ticket_type_proto_depIdxs = []int32{
	3, // 0: getway.ListTicketTypeResp.list:type_name -> getway.TicketTypeData
	0, // 1: getway.TicketTypeServices.GetTicketType:input_type -> getway.GetTicketTypeReq
	2, // 2: getway.TicketTypeServices.ListTicketType:input_type -> getway.ListTicketTypeReq
	1, // 3: getway.TicketTypeServices.GetTicketType:output_type -> getway.GetTicketTypeResp
	4, // 4: getway.TicketTypeServices.ListTicketType:output_type -> getway.ListTicketTypeResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ticket_type_proto_init() }
func file_ticket_type_proto_init() {
	if File_ticket_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ticket_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTicketTypeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTicketTypeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTicketTypeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketTypeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTicketTypeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ticket_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_type_proto_goTypes,
		DependencyIndexes: file_ticket_type_proto_depIdxs,
		MessageInfos:      file_ticket_type_proto_msgTypes,
	}.Build()
	File_ticket_type_proto = out.File
	file_ticket_type_proto_rawDesc = nil
	file_ticket_type_proto_goTypes = nil
	file_ticket_type_proto_depIdxs = nil
}
