// Code generated by hertz generator.

package main

import (
	"context"
	"sale/pkg/rdb"
	ws_services "ws-getway/biz/handler"
	"ws-getway/biz/hub"
	"ws-getway/biz/queue"
	"ws-getway/biz/subscriber"
	"ws-getway/config"
	"ws-getway/mvw"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	config.Init()
	h := server.Default()
	config.Init()
	mvw.InitJwt()
	ctx := context.Background()
	rdbClient := rdb.NewRdbClient(config.C.Data.GetRedis())
	hb := hub.NewHub()
	ws_services.InitWS(hb)
	// 4. 排队大厅三件套
	qm := queue.NewManager(rdbClient, queue.DefaultRate)
	ws_services.InitQueue(qm)
	go queue.NewDispatcher(qm, rdbClient).Run(ctx) // 放行调度器（内部选主，仅 leader 放行）
	go queue.NewBroadcaster(qm, hb).Run(ctx)       // 位次推送（每实例都跑，本地过滤）

	// 5. 订阅 Redis 广播：秒杀结果 + 排队放行事件（必须在对外服务前启动，避免窗口期丢推送）
	go subscriber.NewSubscriber(rdbClient, hb).Run(ctx)
	go subscriber.NewSubscriber(rdbClient, hb).Run(ctx)
	register(h)
	h.Spin()
}
