// Code generated by hertz generator.

package main

import (
	"context"
	ws_services "ws-getway/biz/handler"
	"ws-getway/mvw"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.String(200, "pong")
	})
	r.GET("/ws", append(mvw.AuthMiddleware(), ws_services.GetWS())...)
	// 排队大厅 HTTP 接口：全部登录可见
	api := r.Group("/api", mvw.AuthMiddleware()...)
	api.POST("/queue/:event_id/join", ws_services.JoinQueue)
	api.GET("/queue/:event_id/position", ws_services.QueuePosition)
	api.DELETE("/queue/:event_id", ws_services.LeaveQueue)
	api.GET("/queue/:event_id/length", ws_services.QueueLength)
}
