// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: show/v1/show.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Show_CreateShow_FullMethodName   = "/api.show.v1.Show/CreateShow"
	Show_UpdateShow_FullMethodName   = "/api.show.v1.Show/UpdateShow"
	Show_DeleteShow_FullMethodName   = "/api.show.v1.Show/DeleteShow"
	Show_GetShow_FullMethodName      = "/api.show.v1.Show/GetShow"
	Show_ListShow_FullMethodName     = "/api.show.v1.Show/ListShow"
	Show_UpdateStatus_FullMethodName = "/api.show.v1.Show/UpdateStatus"
	Show_GetEventShow_FullMethodName = "/api.show.v1.Show/GetEventShow"
)

// ShowClient is the client API for Show service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShowClient interface {
	CreateShow(ctx context.Context, in *CreateShowRequest, opts ...grpc.CallOption) (*CreateShowReply, error)
	UpdateShow(ctx context.Context, in *UpdateShowRequest, opts ...grpc.CallOption) (*UpdateShowReply, error)
	DeleteShow(ctx context.Context, in *DeleteShowRequest, opts ...grpc.CallOption) (*DeleteShowReply, error)
	GetShow(ctx context.Context, in *GetShowRequest, opts ...grpc.CallOption) (*GetShowReply, error)
	ListShow(ctx context.Context, in *ListShowRequest, opts ...grpc.CallOption) (*ListShowReply, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusReply, error)
	GetEventShow(ctx context.Context, in *GetEventShowRequest, opts ...grpc.CallOption) (*GetEventShowReply, error)
}

type showClient struct {
	cc grpc.ClientConnInterface
}

func NewShowClient(cc grpc.ClientConnInterface) ShowClient {
	return &showClient{cc}
}

func (c *showClient) CreateShow(ctx context.Context, in *CreateShowRequest, opts ...grpc.CallOption) (*CreateShowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShowReply)
	err := c.cc.Invoke(ctx, Show_CreateShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showClient) UpdateShow(ctx context.Context, in *UpdateShowRequest, opts ...grpc.CallOption) (*UpdateShowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateShowReply)
	err := c.cc.Invoke(ctx, Show_UpdateShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showClient) DeleteShow(ctx context.Context, in *DeleteShowRequest, opts ...grpc.CallOption) (*DeleteShowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShowReply)
	err := c.cc.Invoke(ctx, Show_DeleteShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showClient) GetShow(ctx context.Context, in *GetShowRequest, opts ...grpc.CallOption) (*GetShowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShowReply)
	err := c.cc.Invoke(ctx, Show_GetShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showClient) ListShow(ctx context.Context, in *ListShowRequest, opts ...grpc.CallOption) (*ListShowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShowReply)
	err := c.cc.Invoke(ctx, Show_ListShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatusReply)
	err := c.cc.Invoke(ctx, Show_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showClient) GetEventShow(ctx context.Context, in *GetEventShowRequest, opts ...grpc.CallOption) (*GetEventShowReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventShowReply)
	err := c.cc.Invoke(ctx, Show_GetEventShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShowServer is the server API for Show service.
// All implementations must embed UnimplementedShowServer
// for forward compatibility.
type ShowServer interface {
	CreateShow(context.Context, *CreateShowRequest) (*CreateShowReply, error)
	UpdateShow(context.Context, *UpdateShowRequest) (*UpdateShowReply, error)
	DeleteShow(context.Context, *DeleteShowRequest) (*DeleteShowReply, error)
	GetShow(context.Context, *GetShowRequest) (*GetShowReply, error)
	ListShow(context.Context, *ListShowRequest) (*ListShowReply, error)
	UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusReply, error)
	GetEventShow(context.Context, *GetEventShowRequest) (*GetEventShowReply, error)
	mustEmbedUnimplementedShowServer()
}

// UnimplementedShowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShowServer struct{}

func (UnimplementedShowServer) CreateShow(context.Context, *CreateShowRequest) (*CreateShowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShow not implemented")
}
func (UnimplementedShowServer) UpdateShow(context.Context, *UpdateShowRequest) (*UpdateShowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShow not implemented")
}
func (UnimplementedShowServer) DeleteShow(context.Context, *DeleteShowRequest) (*DeleteShowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShow not implemented")
}
func (UnimplementedShowServer) GetShow(context.Context, *GetShowRequest) (*GetShowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShow not implemented")
}
func (UnimplementedShowServer) ListShow(context.Context, *ListShowRequest) (*ListShowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShow not implemented")
}
func (UnimplementedShowServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedShowServer) GetEventShow(context.Context, *GetEventShowRequest) (*GetEventShowReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventShow not implemented")
}
func (UnimplementedShowServer) mustEmbedUnimplementedShowServer() {}
func (UnimplementedShowServer) testEmbeddedByValue()              {}

// UnsafeShowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShowServer will
// result in compilation errors.
type UnsafeShowServer interface {
	mustEmbedUnimplementedShowServer()
}

func RegisterShowServer(s grpc.ServiceRegistrar, srv ShowServer) {
	// If the following call panics, it indicates UnimplementedShowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Show_ServiceDesc, srv)
}

func _Show_CreateShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowServer).CreateShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Show_CreateShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowServer).CreateShow(ctx, req.(*CreateShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Show_UpdateShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowServer).UpdateShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Show_UpdateShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowServer).UpdateShow(ctx, req.(*UpdateShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Show_DeleteShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowServer).DeleteShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Show_DeleteShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowServer).DeleteShow(ctx, req.(*DeleteShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Show_GetShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowServer).GetShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Show_GetShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowServer).GetShow(ctx, req.(*GetShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Show_ListShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowServer).ListShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Show_ListShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowServer).ListShow(ctx, req.(*ListShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Show_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Show_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Show_GetEventShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowServer).GetEventShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Show_GetEventShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowServer).GetEventShow(ctx, req.(*GetEventShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Show_ServiceDesc is the grpc.ServiceDesc for Show service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Show_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.show.v1.Show",
	HandlerType: (*ShowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShow",
			Handler:    _Show_CreateShow_Handler,
		},
		{
			MethodName: "UpdateShow",
			Handler:    _Show_UpdateShow_Handler,
		},
		{
			MethodName: "DeleteShow",
			Handler:    _Show_DeleteShow_Handler,
		},
		{
			MethodName: "GetShow",
			Handler:    _Show_GetShow_Handler,
		},
		{
			MethodName: "ListShow",
			Handler:    _Show_ListShow_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _Show_UpdateStatus_Handler,
		},
		{
			MethodName: "GetEventShow",
			Handler:    _Show_GetEventShow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "show/v1/show.proto",
}
