// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: show/v1/show.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,3,opt,name=show_time,json=showTime,proto3" json:"show_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	SoldCount     int32                  `protobuf:"varint,6,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShowRequest) Reset() {
	*x = CreateShowRequest{}
	mi := &file_show_v1_show_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowRequest) ProtoMessage() {}

func (x *CreateShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowRequest.ProtoReflect.Descriptor instead.
func (*CreateShowRequest) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShowRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateShowRequest) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *CreateShowRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateShowRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateShowRequest) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *CreateShowRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateShowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" json:"show_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	SoldCount     int32                  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	SortOrder     int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShowReply) Reset() {
	*x = CreateShowReply{}
	mi := &file_show_v1_show_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowReply) ProtoMessage() {}

func (x *CreateShowReply) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowReply.ProtoReflect.Descriptor instead.
func (*CreateShowReply) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShowReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateShowReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateShowReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateShowReply) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *CreateShowReply) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateShowReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateShowReply) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateShowReply) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *CreateShowReply) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" json:"show_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        *string                `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	SoldCount     int32                  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	SortOrder     int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShowRequest) Reset() {
	*x = UpdateShowRequest{}
	mi := &file_show_v1_show_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShowRequest) ProtoMessage() {}

func (x *UpdateShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShowRequest.ProtoReflect.Descriptor instead.
func (*UpdateShowRequest) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateShowRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateShowRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *UpdateShowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateShowRequest) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *UpdateShowRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateShowRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateShowRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateShowRequest) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *UpdateShowRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateShowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" json:"show_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        *string                `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	SoldCount     int32                  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	SortOrder     int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShowReply) Reset() {
	*x = UpdateShowReply{}
	mi := &file_show_v1_show_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShowReply) ProtoMessage() {}

func (x *UpdateShowReply) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShowReply.ProtoReflect.Descriptor instead.
func (*UpdateShowReply) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateShowReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateShowReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *UpdateShowReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateShowReply) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *UpdateShowReply) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateShowReply) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateShowReply) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateShowReply) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *UpdateShowReply) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type DeleteShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShowRequest) Reset() {
	*x = DeleteShowRequest{}
	mi := &file_show_v1_show_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShowRequest) ProtoMessage() {}

func (x *DeleteShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShowRequest.ProtoReflect.Descriptor instead.
func (*DeleteShowRequest) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteShowRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteShowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShowReply) Reset() {
	*x = DeleteShowReply{}
	mi := &file_show_v1_show_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShowReply) ProtoMessage() {}

func (x *DeleteShowReply) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShowReply.ProtoReflect.Descriptor instead.
func (*DeleteShowReply) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{5}
}

type GetShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowRequest) Reset() {
	*x = GetShowRequest{}
	mi := &file_show_v1_show_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowRequest) ProtoMessage() {}

func (x *GetShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowRequest.ProtoReflect.Descriptor instead.
func (*GetShowRequest) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{6}
}

func (x *GetShowRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetShowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" json:"show_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	SoldCount     int32                  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	SortOrder     int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowReply) Reset() {
	*x = GetShowReply{}
	mi := &file_show_v1_show_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowReply) ProtoMessage() {}

func (x *GetShowReply) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowReply.ProtoReflect.Descriptor instead.
func (*GetShowReply) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{7}
}

func (x *GetShowReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetShowReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *GetShowReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetShowReply) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *GetShowReply) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetShowReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetShowReply) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetShowReply) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *GetShowReply) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ShowData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" json:"show_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	SoldCount     int32                  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	SortOrder     int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowData) Reset() {
	*x = ShowData{}
	mi := &file_show_v1_show_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowData) ProtoMessage() {}

func (x *ShowData) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowData.ProtoReflect.Descriptor instead.
func (*ShowData) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{8}
}

func (x *ShowData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShowData) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ShowData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShowData) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *ShowData) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ShowData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShowData) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ShowData) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *ShowData) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ListShowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Page  int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size  int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// 过滤维度：按活动 / 状态(draft/on_sale/closed 等) 下钻
	EventId       int64   `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        *string `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowRequest) Reset() {
	*x = ListShowRequest{}
	mi := &file_show_v1_show_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowRequest) ProtoMessage() {}

func (x *ListShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowRequest.ProtoReflect.Descriptor instead.
func (*ListShowRequest) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{9}
}

func (x *ListShowRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShowRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListShowRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ListShowRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type ListShowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ShowData            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowReply) Reset() {
	*x = ListShowReply{}
	mi := &file_show_v1_show_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowReply) ProtoMessage() {}

func (x *ListShowReply) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowReply.ProtoReflect.Descriptor instead.
func (*ListShowReply) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{10}
}

func (x *ListShowReply) GetList() []*ShowData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListShowReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_show_v1_show_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusReply) Reset() {
	*x = UpdateStatusReply{}
	mi := &file_show_v1_show_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReply) ProtoMessage() {}

func (x *UpdateStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReply.ProtoReflect.Descriptor instead.
func (*UpdateStatusReply) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{12}
}

type GetEventShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventShowRequest) Reset() {
	*x = GetEventShowRequest{}
	mi := &file_show_v1_show_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventShowRequest) ProtoMessage() {}

func (x *GetEventShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventShowRequest.ProtoReflect.Descriptor instead.
func (*GetEventShowRequest) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{13}
}

func (x *GetEventShowRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEventShowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShowTime      string                 `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" json:"show_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	SoldCount     int32                  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	SortOrder     int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventShowReply) Reset() {
	*x = GetEventShowReply{}
	mi := &file_show_v1_show_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventShowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventShowReply) ProtoMessage() {}

func (x *GetEventShowReply) ProtoReflect() protoreflect.Message {
	mi := &file_show_v1_show_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventShowReply.ProtoReflect.Descriptor instead.
func (*GetEventShowReply) Descriptor() ([]byte, []int) {
	return file_show_v1_show_proto_rawDescGZIP(), []int{14}
}

func (x *GetEventShowReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEventShowReply) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *GetEventShowReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEventShowReply) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *GetEventShowReply) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetEventShowReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetEventShowReply) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetEventShowReply) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *GetEventShowReply) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

var File_show_v1_show_proto protoreflect.FileDescriptor

const file_show_v1_show_proto_rawDesc = "" +
	"\n" +
	"\x12show/v1/show.proto\x12\vapi.show.v1\"\xce\x01\n" +
	"\x11CreateShowRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tshow_time\x18\x03 \x01(\tR\bshowTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\x06 \x01(\x05R\tsoldCount\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\"\xf4\x01\n" +
	"\x0fCreateShowReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tshow_time\x18\x04 \x01(\tR\bshowTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\b \x01(\x05R\tsoldCount\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder\"\x86\x02\n" +
	"\x11UpdateShowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tshow_time\x18\x04 \x01(\tR\bshowTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\b \x01(\x05R\tsoldCount\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrderB\t\n" +
	"\a_status\"\x84\x02\n" +
	"\x0fUpdateShowReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tshow_time\x18\x04 \x01(\tR\bshowTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\b \x01(\x05R\tsoldCount\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrderB\t\n" +
	"\a_status\"#\n" +
	"\x11DeleteShowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fDeleteShowReply\" \n" +
	"\x0eGetShowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xf1\x01\n" +
	"\fGetShowReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tshow_time\x18\x04 \x01(\tR\bshowTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\b \x01(\x05R\tsoldCount\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder\"\xed\x01\n" +
	"\bShowData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tshow_time\x18\x04 \x01(\tR\bshowTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\b \x01(\x05R\tsoldCount\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder\"|\n" +
	"\x0fListShowRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"P\n" +
	"\rListShowReply\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.api.show.v1.ShowDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"=\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x13\n" +
	"\x11UpdateStatusReply\"%\n" +
	"\x13GetEventShowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xf6\x01\n" +
	"\x11GetEventShowReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tshow_time\x18\x04 \x01(\tR\bshowTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\b \x01(\x05R\tsoldCount\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder2\x97\x04\n" +
	"\x04Show\x12J\n" +
	"\n" +
	"CreateShow\x12\x1e.api.show.v1.CreateShowRequest\x1a\x1c.api.show.v1.CreateShowReply\x12J\n" +
	"\n" +
	"UpdateShow\x12\x1e.api.show.v1.UpdateShowRequest\x1a\x1c.api.show.v1.UpdateShowReply\x12J\n" +
	"\n" +
	"DeleteShow\x12\x1e.api.show.v1.DeleteShowRequest\x1a\x1c.api.show.v1.DeleteShowReply\x12A\n" +
	"\aGetShow\x12\x1b.api.show.v1.GetShowRequest\x1a\x19.api.show.v1.GetShowReply\x12D\n" +
	"\bListShow\x12\x1c.api.show.v1.ListShowRequest\x1a\x1a.api.show.v1.ListShowReply\x12P\n" +
	"\fUpdateStatus\x12 .api.show.v1.UpdateStatusRequest\x1a\x1e.api.show.v1.UpdateStatusReply\x12P\n" +
	"\fGetEventShow\x12 .api.show.v1.GetEventShowRequest\x1a\x1e.api.show.v1.GetEventShowReplyB%\n" +
	"\vapi.show.v1P\x01Z\x14admin/api/show/v1;v1b\x06proto3"

var (
	file_show_v1_show_proto_rawDescOnce sync.Once
	file_show_v1_show_proto_rawDescData []byte
)

func file_show_v1_show_proto_rawDescGZIP() []byte {
	file_show_v1_show_proto_rawDescOnce.Do(func() {
		file_show_v1_show_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_show_v1_show_proto_rawDesc), len(file_show_v1_show_proto_rawDesc)))
	})
	return file_show_v1_show_proto_rawDescData
}

var file_show_v1_show_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_show_v1_show_proto_goTypes = []any{
	(*CreateShowRequest)(nil),   // 0: api.show.v1.CreateShowRequest
	(*CreateShowReply)(nil),     // 1: api.show.v1.CreateShowReply
	(*UpdateShowRequest)(nil),   // 2: api.show.v1.UpdateShowRequest
	(*UpdateShowReply)(nil),     // 3: api.show.v1.UpdateShowReply
	(*DeleteShowRequest)(nil),   // 4: api.show.v1.DeleteShowRequest
	(*DeleteShowReply)(nil),     // 5: api.show.v1.DeleteShowReply
	(*GetShowRequest)(nil),      // 6: api.show.v1.GetShowRequest
	(*GetShowReply)(nil),        // 7: api.show.v1.GetShowReply
	(*ShowData)(nil),            // 8: api.show.v1.ShowData
	(*ListShowRequest)(nil),     // 9: api.show.v1.ListShowRequest
	(*ListShowReply)(nil),       // 10: api.show.v1.ListShowReply
	(*UpdateStatusRequest)(nil), // 11: api.show.v1.UpdateStatusRequest
	(*UpdateStatusReply)(nil),   // 12: api.show.v1.UpdateStatusReply
	(*GetEventShowRequest)(nil), // 13: api.show.v1.GetEventShowRequest
	(*GetEventShowReply)(nil),   // 14: api.show.v1.GetEventShowReply
}
var file_show_v1_show_proto_depIdxs = []int32{
	8,  // 0: api.show.v1.ListShowReply.list:type_name -> api.show.v1.ShowData
	0,  // 1: api.show.v1.Show.CreateShow:input_type -> api.show.v1.CreateShowRequest
	2,  // 2: api.show.v1.Show.UpdateShow:input_type -> api.show.v1.UpdateShowRequest
	4,  // 3: api.show.v1.Show.DeleteShow:input_type -> api.show.v1.DeleteShowRequest
	6,  // 4: api.show.v1.Show.GetShow:input_type -> api.show.v1.GetShowRequest
	9,  // 5: api.show.v1.Show.ListShow:input_type -> api.show.v1.ListShowRequest
	11, // 6: api.show.v1.Show.UpdateStatus:input_type -> api.show.v1.UpdateStatusRequest
	13, // 7: api.show.v1.Show.GetEventShow:input_type -> api.show.v1.GetEventShowRequest
	1,  // 8: api.show.v1.Show.CreateShow:output_type -> api.show.v1.CreateShowReply
	3,  // 9: api.show.v1.Show.UpdateShow:output_type -> api.show.v1.UpdateShowReply
	5,  // 10: api.show.v1.Show.DeleteShow:output_type -> api.show.v1.DeleteShowReply
	7,  // 11: api.show.v1.Show.GetShow:output_type -> api.show.v1.GetShowReply
	10, // 12: api.show.v1.Show.ListShow:output_type -> api.show.v1.ListShowReply
	12, // 13: api.show.v1.Show.UpdateStatus:output_type -> api.show.v1.UpdateStatusReply
	14, // 14: api.show.v1.Show.GetEventShow:output_type -> api.show.v1.GetEventShowReply
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_show_v1_show_proto_init() }
func file_show_v1_show_proto_init() {
	if File_show_v1_show_proto != nil {
		return
	}
	file_show_v1_show_proto_msgTypes[2].OneofWrappers = []any{}
	file_show_v1_show_proto_msgTypes[3].OneofWrappers = []any{}
	file_show_v1_show_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_show_v1_show_proto_rawDesc), len(file_show_v1_show_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_show_v1_show_proto_goTypes,
		DependencyIndexes: file_show_v1_show_proto_depIdxs,
		MessageInfos:      file_show_v1_show_proto_msgTypes,
	}.Build()
	File_show_v1_show_proto = out.File
	file_show_v1_show_proto_goTypes = nil
	file_show_v1_show_proto_depIdxs = nil
}
