// Code generated by hertz generator.

package promo

import (
	"getway/mvw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return mvw.AuthMiddleware()
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _promosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpromoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepromoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _promos0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpromoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validatepromoMw() []app.HandlerFunc {
	// your code...
	return nil
}
