// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: transfer/v1/transfer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int64                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	TransferType  string                 `protobuf:"bytes,4,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransferRequest) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *CreateTransferRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *CreateTransferRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *CreateTransferRequest) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *CreateTransferRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTransferRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateTransferReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TransferType  string                 `protobuf:"bytes,6,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferReply) Reset() {
	*x = CreateTransferReply{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferReply) ProtoMessage() {}

func (x *CreateTransferReply) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferReply.ProtoReflect.Descriptor instead.
func (*CreateTransferReply) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransferReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateTransferReply) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *CreateTransferReply) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *CreateTransferReply) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *CreateTransferReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTransferReply) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *CreateTransferReply) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTransferReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Status        *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	TransferType  string                 `protobuf:"bytes,6,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	ReviewedBy    *int64                 `protobuf:"varint,9,opt,name=reviewed_by,json=reviewedBy,proto3,oneof" json:"reviewed_by,omitempty"`
	ReviewedAt    *string                `protobuf:"bytes,10,opt,name=reviewed_at,json=reviewedAt,proto3,oneof" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransferRequest) Reset() {
	*x = UpdateTransferRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransferRequest) ProtoMessage() {}

func (x *UpdateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransferRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTransferRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTransferRequest) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *UpdateTransferRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *UpdateTransferRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *UpdateTransferRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateTransferRequest) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *UpdateTransferRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTransferRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateTransferRequest) GetReviewedBy() int64 {
	if x != nil && x.ReviewedBy != nil {
		return *x.ReviewedBy
	}
	return 0
}

func (x *UpdateTransferRequest) GetReviewedAt() string {
	if x != nil && x.ReviewedAt != nil {
		return *x.ReviewedAt
	}
	return ""
}

type UpdateTransferReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Status        *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	TransferType  string                 `protobuf:"bytes,6,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	ReviewedBy    *int64                 `protobuf:"varint,9,opt,name=reviewed_by,json=reviewedBy,proto3,oneof" json:"reviewed_by,omitempty"`
	ReviewedAt    *string                `protobuf:"bytes,10,opt,name=reviewed_at,json=reviewedAt,proto3,oneof" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransferReply) Reset() {
	*x = UpdateTransferReply{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransferReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransferReply) ProtoMessage() {}

func (x *UpdateTransferReply) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransferReply.ProtoReflect.Descriptor instead.
func (*UpdateTransferReply) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTransferReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTransferReply) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *UpdateTransferReply) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *UpdateTransferReply) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *UpdateTransferReply) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateTransferReply) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *UpdateTransferReply) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTransferReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateTransferReply) GetReviewedBy() int64 {
	if x != nil && x.ReviewedBy != nil {
		return *x.ReviewedBy
	}
	return 0
}

func (x *UpdateTransferReply) GetReviewedAt() string {
	if x != nil && x.ReviewedAt != nil {
		return *x.ReviewedAt
	}
	return ""
}

type DeleteTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransferRequest) Reset() {
	*x = DeleteTransferRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransferRequest) ProtoMessage() {}

func (x *DeleteTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransferRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTransferRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTransferReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransferReply) Reset() {
	*x = DeleteTransferReply{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransferReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransferReply) ProtoMessage() {}

func (x *DeleteTransferReply) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransferReply.ProtoReflect.Descriptor instead.
func (*DeleteTransferReply) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{5}
}

type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransferRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTransferReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TransferType  string                 `protobuf:"bytes,6,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	ReviewedBy    *int64                 `protobuf:"varint,9,opt,name=reviewed_by,json=reviewedBy,proto3,oneof" json:"reviewed_by,omitempty"`
	ReviewedAt    *string                `protobuf:"bytes,10,opt,name=reviewed_at,json=reviewedAt,proto3,oneof" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferReply) Reset() {
	*x = GetTransferReply{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferReply) ProtoMessage() {}

func (x *GetTransferReply) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferReply.ProtoReflect.Descriptor instead.
func (*GetTransferReply) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransferReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTransferReply) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *GetTransferReply) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *GetTransferReply) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *GetTransferReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTransferReply) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *GetTransferReply) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetTransferReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetTransferReply) GetReviewedBy() int64 {
	if x != nil && x.ReviewedBy != nil {
		return *x.ReviewedBy
	}
	return 0
}

func (x *GetTransferReply) GetReviewedAt() string {
	if x != nil && x.ReviewedAt != nil {
		return *x.ReviewedAt
	}
	return ""
}

type TransferData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TransferType  string                 `protobuf:"bytes,6,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	ReviewedBy    *int64                 `protobuf:"varint,9,opt,name=reviewed_by,json=reviewedBy,proto3,oneof" json:"reviewed_by,omitempty"`
	ReviewedAt    *string                `protobuf:"bytes,10,opt,name=reviewed_at,json=reviewedAt,proto3,oneof" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferData) Reset() {
	*x = TransferData{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferData) ProtoMessage() {}

func (x *TransferData) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferData.ProtoReflect.Descriptor instead.
func (*TransferData) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{8}
}

func (x *TransferData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferData) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *TransferData) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *TransferData) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *TransferData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferData) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *TransferData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TransferData) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TransferData) GetReviewedBy() int64 {
	if x != nil && x.ReviewedBy != nil {
		return *x.ReviewedBy
	}
	return 0
}

func (x *TransferData) GetReviewedAt() string {
	if x != nil && x.ReviewedAt != nil {
		return *x.ReviewedAt
	}
	return ""
}

type ListTransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Page  int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size  int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// 过滤维度：按票 / 转出方 / 接收方 / 审核状态 / 转让类型下钻
	TicketId      int64   `protobuf:"varint,3,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	FromUserId    int64   `protobuf:"varint,4,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64   `protobuf:"varint,5,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Status        *string `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	TransferType  *string `protobuf:"bytes,7,opt,name=transfer_type,json=transferType,proto3,oneof" json:"transfer_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransferRequest) Reset() {
	*x = ListTransferRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransferRequest) ProtoMessage() {}

func (x *ListTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransferRequest.ProtoReflect.Descriptor instead.
func (*ListTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{9}
}

func (x *ListTransferRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransferRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListTransferRequest) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *ListTransferRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *ListTransferRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *ListTransferRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListTransferRequest) GetTransferType() string {
	if x != nil && x.TransferType != nil {
		return *x.TransferType
	}
	return ""
}

type ListTransferReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TransferData        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransferReply) Reset() {
	*x = ListTransferReply{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransferReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransferReply) ProtoMessage() {}

func (x *ListTransferReply) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransferReply.ProtoReflect.Descriptor instead.
func (*ListTransferReply) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{10}
}

func (x *ListTransferReply) GetList() []*TransferData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTransferReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_transfer_v1_transfer_proto protoreflect.FileDescriptor

const file_transfer_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1atransfer/v1/transfer.proto\x12\x0fapi.transfer.v1\"\xc7\x01\n" +
	"\x15CreateTransferRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x03R\bticketId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x03R\btoUserId\x12#\n" +
	"\rtransfer_type\x18\x04 \x01(\tR\ftransferType\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\xed\x01\n" +
	"\x13CreateTransferReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\x03R\btoUserId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rtransfer_type\x18\x06 \x01(\tR\ftransferType\x12\x14\n" +
	"\x05price\x18\a \x01(\x02R\x05price\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\"\xeb\x02\n" +
	"\x15UpdateTransferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\x03R\btoUserId\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x00R\x06status\x88\x01\x01\x12#\n" +
	"\rtransfer_type\x18\x06 \x01(\tR\ftransferType\x12\x14\n" +
	"\x05price\x18\a \x01(\x02R\x05price\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12$\n" +
	"\vreviewed_by\x18\t \x01(\x03H\x01R\n" +
	"reviewedBy\x88\x01\x01\x12$\n" +
	"\vreviewed_at\x18\n" +
	" \x01(\tH\x02R\n" +
	"reviewedAt\x88\x01\x01B\t\n" +
	"\a_statusB\x0e\n" +
	"\f_reviewed_byB\x0e\n" +
	"\f_reviewed_at\"\xe9\x02\n" +
	"\x13UpdateTransferReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\x03R\btoUserId\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x00R\x06status\x88\x01\x01\x12#\n" +
	"\rtransfer_type\x18\x06 \x01(\tR\ftransferType\x12\x14\n" +
	"\x05price\x18\a \x01(\x02R\x05price\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12$\n" +
	"\vreviewed_by\x18\t \x01(\x03H\x01R\n" +
	"reviewedBy\x88\x01\x01\x12$\n" +
	"\vreviewed_at\x18\n" +
	" \x01(\tH\x02R\n" +
	"reviewedAt\x88\x01\x01B\t\n" +
	"\a_statusB\x0e\n" +
	"\f_reviewed_byB\x0e\n" +
	"\f_reviewed_at\"'\n" +
	"\x15DeleteTransferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13DeleteTransferReply\"$\n" +
	"\x12GetTransferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd6\x02\n" +
	"\x10GetTransferReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\x03R\btoUserId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rtransfer_type\x18\x06 \x01(\tR\ftransferType\x12\x14\n" +
	"\x05price\x18\a \x01(\x02R\x05price\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12$\n" +
	"\vreviewed_by\x18\t \x01(\x03H\x00R\n" +
	"reviewedBy\x88\x01\x01\x12$\n" +
	"\vreviewed_at\x18\n" +
	" \x01(\tH\x01R\n" +
	"reviewedAt\x88\x01\x01B\x0e\n" +
	"\f_reviewed_byB\x0e\n" +
	"\f_reviewed_at\"\xd2\x02\n" +
	"\fTransferData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\x03R\btoUserId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rtransfer_type\x18\x06 \x01(\tR\ftransferType\x12\x14\n" +
	"\x05price\x18\a \x01(\x02R\x05price\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12$\n" +
	"\vreviewed_by\x18\t \x01(\x03H\x00R\n" +
	"reviewedBy\x88\x01\x01\x12$\n" +
	"\vreviewed_at\x18\n" +
	" \x01(\tH\x01R\n" +
	"reviewedAt\x88\x01\x01B\x0e\n" +
	"\f_reviewed_byB\x0e\n" +
	"\f_reviewed_at\"\xfe\x01\n" +
	"\x13ListTransferRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1b\n" +
	"\tticket_id\x18\x03 \x01(\x03R\bticketId\x12 \n" +
	"\ffrom_user_id\x18\x04 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x05 \x01(\x03R\btoUserId\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x00R\x06status\x88\x01\x01\x12(\n" +
	"\rtransfer_type\x18\a \x01(\tH\x01R\ftransferType\x88\x01\x01B\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_transfer_type\"\\\n" +
	"\x11ListTransferReply\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.api.transfer.v1.TransferDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xdb\x03\n" +
	"\bTransfer\x12^\n" +
	"\x0eCreateTransfer\x12&.api.transfer.v1.CreateTransferRequest\x1a$.api.transfer.v1.CreateTransferReply\x12^\n" +
	"\x0eUpdateTransfer\x12&.api.transfer.v1.UpdateTransferRequest\x1a$.api.transfer.v1.UpdateTransferReply\x12^\n" +
	"\x0eDeleteTransfer\x12&.api.transfer.v1.DeleteTransferRequest\x1a$.api.transfer.v1.DeleteTransferReply\x12U\n" +
	"\vGetTransfer\x12#.api.transfer.v1.GetTransferRequest\x1a!.api.transfer.v1.GetTransferReply\x12X\n" +
	"\fListTransfer\x12$.api.transfer.v1.ListTransferRequest\x1a\".api.transfer.v1.ListTransferReplyB-\n" +
	"\x0fapi.transfer.v1P\x01Z\x18admin/api/transfer/v1;v1b\x06proto3"

var (
	file_transfer_v1_transfer_proto_rawDescOnce sync.Once
	file_transfer_v1_transfer_proto_rawDescData []byte
)

func file_transfer_v1_transfer_proto_rawDescGZIP() []byte {
	file_transfer_v1_transfer_proto_rawDescOnce.Do(func() {
		file_transfer_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_v1_transfer_proto_rawDesc), len(file_transfer_v1_transfer_proto_rawDesc)))
	})
	return file_transfer_v1_transfer_proto_rawDescData
}

var file_transfer_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_transfer_v1_transfer_proto_goTypes = []any{
	(*CreateTransferRequest)(nil), // 0: api.transfer.v1.CreateTransferRequest
	(*CreateTransferReply)(nil),   // 1: api.transfer.v1.CreateTransferReply
	(*UpdateTransferRequest)(nil), // 2: api.transfer.v1.UpdateTransferRequest
	(*UpdateTransferReply)(nil),   // 3: api.transfer.v1.UpdateTransferReply
	(*DeleteTransferRequest)(nil), // 4: api.transfer.v1.DeleteTransferRequest
	(*DeleteTransferReply)(nil),   // 5: api.transfer.v1.DeleteTransferReply
	(*GetTransferRequest)(nil),    // 6: api.transfer.v1.GetTransferRequest
	(*GetTransferReply)(nil),      // 7: api.transfer.v1.GetTransferReply
	(*TransferData)(nil),          // 8: api.transfer.v1.TransferData
	(*ListTransferRequest)(nil),   // 9: api.transfer.v1.ListTransferRequest
	(*ListTransferReply)(nil),     // 10: api.transfer.v1.ListTransferReply
}
var file_transfer_v1_transfer_proto_depIdxs = []int32{
	8,  // 0: api.transfer.v1.ListTransferReply.list:type_name -> api.transfer.v1.TransferData
	0,  // 1: api.transfer.v1.Transfer.CreateTransfer:input_type -> api.transfer.v1.CreateTransferRequest
	2,  // 2: api.transfer.v1.Transfer.UpdateTransfer:input_type -> api.transfer.v1.UpdateTransferRequest
	4,  // 3: api.transfer.v1.Transfer.DeleteTransfer:input_type -> api.transfer.v1.DeleteTransferRequest
	6,  // 4: api.transfer.v1.Transfer.GetTransfer:input_type -> api.transfer.v1.GetTransferRequest
	9,  // 5: api.transfer.v1.Transfer.ListTransfer:input_type -> api.transfer.v1.ListTransferRequest
	1,  // 6: api.transfer.v1.Transfer.CreateTransfer:output_type -> api.transfer.v1.CreateTransferReply
	3,  // 7: api.transfer.v1.Transfer.UpdateTransfer:output_type -> api.transfer.v1.UpdateTransferReply
	5,  // 8: api.transfer.v1.Transfer.DeleteTransfer:output_type -> api.transfer.v1.DeleteTransferReply
	7,  // 9: api.transfer.v1.Transfer.GetTransfer:output_type -> api.transfer.v1.GetTransferReply
	10, // 10: api.transfer.v1.Transfer.ListTransfer:output_type -> api.transfer.v1.ListTransferReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_transfer_v1_transfer_proto_init() }
func file_transfer_v1_transfer_proto_init() {
	if File_transfer_v1_transfer_proto != nil {
		return
	}
	file_transfer_v1_transfer_proto_msgTypes[2].OneofWrappers = []any{}
	file_transfer_v1_transfer_proto_msgTypes[3].OneofWrappers = []any{}
	file_transfer_v1_transfer_proto_msgTypes[7].OneofWrappers = []any{}
	file_transfer_v1_transfer_proto_msgTypes[8].OneofWrappers = []any{}
	file_transfer_v1_transfer_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_v1_transfer_proto_rawDesc), len(file_transfer_v1_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfer_v1_transfer_proto_goTypes,
		DependencyIndexes: file_transfer_v1_transfer_proto_depIdxs,
		MessageInfos:      file_transfer_v1_transfer_proto_msgTypes,
	}.Build()
	File_transfer_v1_transfer_proto = out.File
	file_transfer_v1_transfer_proto_goTypes = nil
	file_transfer_v1_transfer_proto_depIdxs = nil
}
