// idl/show/show.proto
// 通用 /api 前缀的 HTTP 契约：getway 接收 HTTP 请求后转发给 activity 服务的
// Show gRPC 接口（activity/api/show/v1/show.proto）。
// 这里只收编 admin.proto 未对接的 RPC：GetShow / ListShow
// （UpdateStatus 已由 admin.proto 的 publish/unpublish 覆盖）。
// 消息字段与上游 proto 一比一对齐，便于 handler 直接透传。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: show.proto

package show

import (
	_ "getway/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
}

func (x *GetShowReq) Reset() {
	*x = GetShowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_show_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowReq) ProtoMessage() {}

func (x *GetShowReq) ProtoReflect() protoreflect.Message {
	mi := &file_show_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowReq.ProtoReflect.Descriptor instead.
func (*GetShowReq) Descriptor() ([]byte, []int) {
	return file_show_proto_rawDescGZIP(), []int{0}
}

func (x *GetShowReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetShowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" form:"id" json:"id,omitempty" query:"id"`
	EventId   int64  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" form:"event_id" json:"event_id,omitempty" query:"event_id"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
	ShowTime  string `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" form:"show_time" json:"show_time,omitempty" query:"show_time"`
	EndTime   string `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" form:"end_time" json:"end_time,omitempty" query:"end_time"`
	Status    string `protobuf:"bytes,6,opt,name=status,proto3" form:"status" json:"status,omitempty" query:"status"`
	Stock     int32  `protobuf:"varint,7,opt,name=stock,proto3" form:"stock" json:"stock,omitempty" query:"stock"`
	SoldCount int32  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" form:"sold_count" json:"sold_count,omitempty" query:"sold_count"`
	SortOrder int32  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" form:"sort_order" json:"sort_order,omitempty" query:"sort_order"`
}

func (x *GetShowResp) Reset() {
	*x = GetShowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_show_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowResp) ProtoMessage() {}

func (x *GetShowResp) ProtoReflect() protoreflect.Message {
	mi := &file_show_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowResp.ProtoReflect.Descriptor instead.
func (*GetShowResp) Descriptor() ([]byte, []int) {
	return file_show_proto_rawDescGZIP(), []int{1}
}

func (x *GetShowResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetShowResp) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *GetShowResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetShowResp) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *GetShowResp) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetShowResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetShowResp) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetShowResp) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *GetShowResp) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ListShowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" query:"page"`
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty" query:"size"`
	// 过滤维度：按活动 / 状态(draft/on_sale/closed 等) 下钻，与上游一致
	EventId int64   `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty" query:"event_id"`
	Status  *string `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty" query:"status"`
}

func (x *ListShowReq) Reset() {
	*x = ListShowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_show_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowReq) ProtoMessage() {}

func (x *ListShowReq) ProtoReflect() protoreflect.Message {
	mi := &file_show_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowReq.ProtoReflect.Descriptor instead.
func (*ListShowReq) Descriptor() ([]byte, []int) {
	return file_show_proto_rawDescGZIP(), []int{2}
}

func (x *ListShowReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShowReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListShowReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ListShowReq) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type ShowData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" form:"id" json:"id,omitempty" query:"id"`
	EventId   int64  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" form:"event_id" json:"event_id,omitempty" query:"event_id"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
	ShowTime  string `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" form:"show_time" json:"show_time,omitempty" query:"show_time"`
	EndTime   string `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" form:"end_time" json:"end_time,omitempty" query:"end_time"`
	Status    string `protobuf:"bytes,6,opt,name=status,proto3" form:"status" json:"status,omitempty" query:"status"`
	Stock     int32  `protobuf:"varint,7,opt,name=stock,proto3" form:"stock" json:"stock,omitempty" query:"stock"`
	SoldCount int32  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" form:"sold_count" json:"sold_count,omitempty" query:"sold_count"`
	SortOrder int32  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" form:"sort_order" json:"sort_order,omitempty" query:"sort_order"`
}

func (x *ShowData) Reset() {
	*x = ShowData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_show_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowData) ProtoMessage() {}

func (x *ShowData) ProtoReflect() protoreflect.Message {
	mi := &file_show_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowData.ProtoReflect.Descriptor instead.
func (*ShowData) Descriptor() ([]byte, []int) {
	return file_show_proto_rawDescGZIP(), []int{3}
}

func (x *ShowData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShowData) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ShowData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShowData) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *ShowData) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ShowData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShowData) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ShowData) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *ShowData) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ListShowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*ShowData `protobuf:"bytes,1,rep,name=list,proto3" form:"list" json:"list,omitempty" query:"list"`
	Total int64       `protobuf:"varint,2,opt,name=total,proto3" form:"total" json:"total,omitempty" query:"total"`
}

func (x *ListShowResp) Reset() {
	*x = ListShowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_show_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowResp) ProtoMessage() {}

func (x *ListShowResp) ProtoReflect() protoreflect.Message {
	mi := &file_show_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowResp.ProtoReflect.Descriptor instead.
func (*ListShowResp) Descriptor() ([]byte, []int) {
	return file_show_proto_rawDescGZIP(), []int{4}
}

func (x *ListShowResp) GetList() []*ShowData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListShowResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetEventShowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
}

func (x *GetEventShowReq) Reset() {
	*x = GetEventShowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_show_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventShowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventShowReq) ProtoMessage() {}

func (x *GetEventShowReq) ProtoReflect() protoreflect.Message {
	mi := &file_show_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventShowReq.ProtoReflect.Descriptor instead.
func (*GetEventShowReq) Descriptor() ([]byte, []int) {
	return file_show_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventShowReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEventShowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" form:"id" json:"id,omitempty" query:"id"`
	EventId   int64  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" form:"event_id" json:"event_id,omitempty" query:"event_id"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
	ShowTime  string `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" form:"show_time" json:"show_time,omitempty" query:"show_time"`
	EndTime   string `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" form:"end_time" json:"end_time,omitempty" query:"end_time"`
	Status    string `protobuf:"bytes,6,opt,name=status,proto3" form:"status" json:"status,omitempty" query:"status"`
	Stock     int32  `protobuf:"varint,7,opt,name=stock,proto3" form:"stock" json:"stock,omitempty" query:"stock"`
	SoldCount int32  `protobuf:"varint,8,opt,name=sold_count,json=soldCount,proto3" form:"sold_count" json:"sold_count,omitempty" query:"sold_count"`
	SortOrder int32  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" form:"sort_order" json:"sort_order,omitempty" query:"sort_order"`
}

func (x *GetEventShowResp) Reset() {
	*x = GetEventShowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_show_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventShowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventShowResp) ProtoMessage() {}

func (x *GetEventShowResp) ProtoReflect() protoreflect.Message {
	mi := &file_show_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventShowResp.ProtoReflect.Descriptor instead.
func (*GetEventShowResp) Descriptor() ([]byte, []int) {
	return file_show_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventShowResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEventShowResp) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *GetEventShowResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEventShowResp) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *GetEventShowResp) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetEventShowResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetEventShowResp) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetEventShowResp) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *GetEventShowResp) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

var File_show_proto protoreflect.FileDescriptor

var file_show_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x65,
	0x74, 0x77, 0x61, 0x79, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x24, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x06, 0xd2, 0xbb, 0x18, 0x02, 0x69,
	0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf0, 0x01, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f,
	0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x73, 0x6f, 0x6c, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x72,
	0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73,
	0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xa6, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x08, 0xb2, 0xbb, 0x18, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x42, 0x08, 0xb2, 0xbb, 0x18, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0c, 0xb2, 0xbb, 0x18, 0x08, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xb2,
	0xbb, 0x18, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0xed, 0x01, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x6c, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x22, 0x4a, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x29, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x06, 0xd2, 0xbb,
	0x18, 0x02, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf5, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x68, 0x6f, 0x77, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x6c, 0x64, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x32, 0xfb, 0x01, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x46, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x12, 0x2e, 0x67,
	0x65, 0x74, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x22, 0x12, 0xca, 0xc1, 0x18, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x68, 0x6f, 0x77, 0x73, 0x2f, 0x3a, 0x69, 0x64, 0x12, 0x45, 0x0a, 0x08, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x13, 0x2e, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x67, 0x65, 0x74,
	0x77, 0x61, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x0e, 0xca, 0xc1, 0x18, 0x0a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x77, 0x73,
	0x12, 0x5c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x77,
	0x12, 0x17, 0x2e, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x67, 0x65, 0x74, 0x77,
	0x61, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x19, 0xca, 0xc1, 0x18, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x2f, 0x3a, 0x69, 0x64, 0x2f, 0x73, 0x68, 0x6f, 0x77, 0x73, 0x42, 0x17,
	0x5a, 0x15, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2f, 0x73, 0x68, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_show_proto_rawDescOnce sync.Once
	file_show_proto_rawDescData = file_show_proto_rawDesc
)

func file_show_proto_rawDescGZIP() []byte {
	file_show_proto_rawDescOnce.Do(func() {
		file_show_proto_rawDescData = protoimpl.X.CompressGZIP(file_show_proto_rawDescData)
	})
	return file_show_proto_rawDescData
}

var file_show_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_show_proto_goTypes = []interface{}{
	(*GetShowReq)(nil),       // 0: getway.GetShowReq
	(*GetShowResp)(nil),      // 1: getway.GetShowResp
	(*ListShowReq)(nil),      // 2: getway.ListShowReq
	(*ShowData)(nil),         // 3: getway.ShowData
	(*ListShowResp)(nil),     // 4: getway.ListShowResp
	(*GetEventShowReq)(nil),  // 5: getway.GetEventShowReq
	(*GetEventShowResp)(nil), // 6: getway.GetEventShowResp
}
var file_show_proto_depIdxs = []int32{
	3, // 0: getway.ListShowResp.list:type_name -> getway.ShowData
	0, // 1: getway.ShowServices.GetShow:input_type -> getway.GetShowReq
	2, // 2: getway.ShowServices.ListShow:input_type -> getway.ListShowReq
	5, // 3: getway.ShowServices.GetEventShow:input_type -> getway.GetEventShowReq
	1, // 4: getway.ShowServices.GetShow:output_type -> getway.GetShowResp
	4, // 5: getway.ShowServices.ListShow:output_type -> getway.ListShowResp
	6, // 6: getway.ShowServices.GetEventShow:output_type -> getway.GetEventShowResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_show_proto_init() }
func file_show_proto_init() {
	if File_show_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_show_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_show_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_show_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_show_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_show_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_show_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventShowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_show_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventShowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_show_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_show_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_show_proto_goTypes,
		DependencyIndexes: file_show_proto_depIdxs,
		MessageInfos:      file_show_proto_msgTypes,
	}.Build()
	File_show_proto = out.File
	file_show_proto_rawDesc = nil
	file_show_proto_goTypes = nil
	file_show_proto_depIdxs = nil
}
