// Code generated by hertz generator.

package ticket

import (
	"getway/mvw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _purchaseMw() []app.HandlerFunc {
	// your code...
	return mvw.SeckillMiddleware()
}
