// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: stats/v1/stats.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stats_GetDashboard_FullMethodName        = "/api.stats.v1.Stats/GetDashboard"
	Stats_ListSalesTrend_FullMethodName      = "/api.stats.v1.Stats/ListSalesTrend"
	Stats_ListTicketTypeStats_FullMethodName = "/api.stats.v1.Stats/ListTicketTypeStats"
	Stats_GetConversionFunnel_FullMethodName = "/api.stats.v1.Stats/GetConversionFunnel"
)

// StatsClient is the client API for Stats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stats 只读统计服务，聚合结构与 model/stats.go 一一对应：
// DashboardStats / SalesTrend / TicketTypeStats / ConversionFunnel。
type StatsClient interface {
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardReply, error)
	ListSalesTrend(ctx context.Context, in *ListSalesTrendRequest, opts ...grpc.CallOption) (*ListSalesTrendReply, error)
	ListTicketTypeStats(ctx context.Context, in *ListTicketTypeStatsRequest, opts ...grpc.CallOption) (*ListTicketTypeStatsReply, error)
	GetConversionFunnel(ctx context.Context, in *GetConversionFunnelRequest, opts ...grpc.CallOption) (*GetConversionFunnelReply, error)
}

type statsClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsClient(cc grpc.ClientConnInterface) StatsClient {
	return &statsClient{cc}
}

func (c *statsClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardReply)
	err := c.cc.Invoke(ctx, Stats_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) ListSalesTrend(ctx context.Context, in *ListSalesTrendRequest, opts ...grpc.CallOption) (*ListSalesTrendReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSalesTrendReply)
	err := c.cc.Invoke(ctx, Stats_ListSalesTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) ListTicketTypeStats(ctx context.Context, in *ListTicketTypeStatsRequest, opts ...grpc.CallOption) (*ListTicketTypeStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTicketTypeStatsReply)
	err := c.cc.Invoke(ctx, Stats_ListTicketTypeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) GetConversionFunnel(ctx context.Context, in *GetConversionFunnelRequest, opts ...grpc.CallOption) (*GetConversionFunnelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversionFunnelReply)
	err := c.cc.Invoke(ctx, Stats_GetConversionFunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServer is the server API for Stats service.
// All implementations must embed UnimplementedStatsServer
// for forward compatibility.
//
// Stats 只读统计服务，聚合结构与 model/stats.go 一一对应：
// DashboardStats / SalesTrend / TicketTypeStats / ConversionFunnel。
type StatsServer interface {
	GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardReply, error)
	ListSalesTrend(context.Context, *ListSalesTrendRequest) (*ListSalesTrendReply, error)
	ListTicketTypeStats(context.Context, *ListTicketTypeStatsRequest) (*ListTicketTypeStatsReply, error)
	GetConversionFunnel(context.Context, *GetConversionFunnelRequest) (*GetConversionFunnelReply, error)
	mustEmbedUnimplementedStatsServer()
}

// UnimplementedStatsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServer struct{}

func (UnimplementedStatsServer) GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedStatsServer) ListSalesTrend(context.Context, *ListSalesTrendRequest) (*ListSalesTrendReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSalesTrend not implemented")
}
func (UnimplementedStatsServer) ListTicketTypeStats(context.Context, *ListTicketTypeStatsRequest) (*ListTicketTypeStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTicketTypeStats not implemented")
}
func (UnimplementedStatsServer) GetConversionFunnel(context.Context, *GetConversionFunnelRequest) (*GetConversionFunnelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversionFunnel not implemented")
}
func (UnimplementedStatsServer) mustEmbedUnimplementedStatsServer() {}
func (UnimplementedStatsServer) testEmbeddedByValue()               {}

// UnsafeStatsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServer will
// result in compilation errors.
type UnsafeStatsServer interface {
	mustEmbedUnimplementedStatsServer()
}

func RegisterStatsServer(s grpc.ServiceRegistrar, srv StatsServer) {
	// If the following call panics, it indicates UnimplementedStatsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stats_ServiceDesc, srv)
}

func _Stats_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_ListSalesTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSalesTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).ListSalesTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_ListSalesTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).ListSalesTrend(ctx, req.(*ListSalesTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_ListTicketTypeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketTypeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).ListTicketTypeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_ListTicketTypeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).ListTicketTypeStats(ctx, req.(*ListTicketTypeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stats_GetConversionFunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversionFunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServer).GetConversionFunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stats_GetConversionFunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServer).GetConversionFunnel(ctx, req.(*GetConversionFunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Stats_ServiceDesc is the grpc.ServiceDesc for Stats service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stats_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.stats.v1.Stats",
	HandlerType: (*StatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboard",
			Handler:    _Stats_GetDashboard_Handler,
		},
		{
			MethodName: "ListSalesTrend",
			Handler:    _Stats_ListSalesTrend_Handler,
		},
		{
			MethodName: "ListTicketTypeStats",
			Handler:    _Stats_ListTicketTypeStats_Handler,
		},
		{
			MethodName: "GetConversionFunnel",
			Handler:    _Stats_GetConversionFunnel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/v1/stats.proto",
}
