// Code generated by hertz generator.

package show

import (
	showv1 "activity/api/show/v1"
	"context"

	"getway/biz/client"
	"getway/biz/handler/response"
	show "getway/biz/model/show"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// GetShow .
// @router /api/shows/:id [GET]
func GetShow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.GetShowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	res, err := client.GetShow().GetShow(ctx, &showv1.GetShowRequest{
		Id: req.GetId(),
	})
	if err != nil {
		hlog.Error(err.Error())
		response.HandleBussinessFail(c, err.Error())
		return
	}
	resp := &show.GetShowResp{
		Id:        res.GetId(),
		EventId:   res.GetEventId(),
		Name:      res.GetName(),
		ShowTime:  res.GetShowTime(),
		EndTime:   res.GetEndTime(),
		Status:    res.GetStatus(),
		Stock:     res.GetStock(),
		SoldCount: res.GetSoldCount(),
		SortOrder: res.GetSortOrder(),
	}
	response.HandleSuccess(c, resp)
}

// ListShow .
// @router /api/shows [GET]
func ListShow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.ListShowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	res, err := client.GetShow().ListShow(ctx, &showv1.ListShowRequest{
		Page:    req.GetPage(),
		Size:    req.GetSize(),
		EventId: req.GetEventId(),
		Status:  req.Status,
	})
	if err != nil {
		hlog.Error(err.Error())
		response.HandleBussinessFail(c, err.Error())
		return
	}
	list := make([]*show.ShowData, 0, len(res.GetList()))
	for _, it := range res.GetList() {
		list = append(list, &show.ShowData{
			Id:        it.GetId(),
			EventId:   it.GetEventId(),
			Name:      it.GetName(),
			ShowTime:  it.GetShowTime(),
			EndTime:   it.GetEndTime(),
			Status:    it.GetStatus(),
			Stock:     it.GetStock(),
			SoldCount: it.GetSoldCount(),
			SortOrder: it.GetSortOrder(),
		})
	}
	resp := &show.ListShowResp{
		List:  list,
		Total: res.GetTotal(),
	}
	response.HandleSuccess(c, resp)
}

// GetEventShow .
// @router /api/events/:id/show [GET]
func GetEventShow(ctx context.Context, c *app.RequestContext) {
	var err error
	var req show.GetEventShowReq
	err = c.BindAndValidate(&req)
	if err != nil {
		response.HandleParamsError(c)
		return
	}

	data, err := client.GetShow().GetEventShow(ctx, &showv1.GetEventShowRequest{
		Id: req.GetId(),
	})
	if err != nil {
		response.HandleBussinessFail(c, err.Error())
		return
	}
	response.HandleSuccess(c, &show.GetEventShowResp{
		Id:        data.GetId(),
		ShowTime:  data.ShowTime,
		EndTime:   data.EndTime,
		EventId:   data.EventId,
		SoldCount: data.SoldCount,
		SortOrder: data.SortOrder,
		Name:      data.Name,
	})
}
