// Code generated by hertz generator.

package main

import (
	"flag"

	"getway/biz/client"

	"getway/config"
	"getway/mvw"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	flag.Parse()
	config.Init()
	h := server.Default()
	mvw.InitJwt()
	client.NewRdb(config.C.Data)
	// mvw.InitTrace()
	client.InitRpcClient()
	h.Use(mvw.LogMiddleware())
	register(h)
	h.Spin()
}
