// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: market/v1/market.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Marketplace_CreateListing_FullMethodName       = "/api.market.v1.Marketplace/CreateListing"
	Marketplace_GetListing_FullMethodName          = "/api.market.v1.Marketplace/GetListing"
	Marketplace_ListActiveListings_FullMethodName  = "/api.market.v1.Marketplace/ListActiveListings"
	Marketplace_ListEventListings_FullMethodName   = "/api.market.v1.Marketplace/ListEventListings"
	Marketplace_ListMyListings_FullMethodName      = "/api.market.v1.Marketplace/ListMyListings"
	Marketplace_ListMyPurchases_FullMethodName     = "/api.market.v1.Marketplace/ListMyPurchases"
	Marketplace_ListTransferHistory_FullMethodName = "/api.market.v1.Marketplace/ListTransferHistory"
	Marketplace_BuyListing_FullMethodName          = "/api.market.v1.Marketplace/BuyListing"
	Marketplace_CancelListing_FullMethodName       = "/api.market.v1.Marketplace/CancelListing"
)

// MarketplaceClient is the client API for Marketplace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Marketplace 二手市场服务：挂牌 CRUD + 转让历史查询。
// 卖家/买家身份由网关从 JWT 解析后通过 user_id 字段传入，
// RPC 服务端信任内网调用方，不再做鉴权。
type MarketplaceClient interface {
	CreateListing(ctx context.Context, in *CreateListingRequest, opts ...grpc.CallOption) (*CreateListingReply, error)
	GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingReply, error)
	ListActiveListings(ctx context.Context, in *ListActiveListingsRequest, opts ...grpc.CallOption) (*ListActiveListingsReply, error)
	ListEventListings(ctx context.Context, in *ListEventListingsRequest, opts ...grpc.CallOption) (*ListEventListingsReply, error)
	ListMyListings(ctx context.Context, in *ListMyListingsRequest, opts ...grpc.CallOption) (*ListMyListingsReply, error)
	ListMyPurchases(ctx context.Context, in *ListMyPurchasesRequest, opts ...grpc.CallOption) (*ListMyPurchasesReply, error)
	ListTransferHistory(ctx context.Context, in *ListTransferHistoryRequest, opts ...grpc.CallOption) (*ListTransferHistoryReply, error)
	BuyListing(ctx context.Context, in *BuyListingRequest, opts ...grpc.CallOption) (*BuyListingReply, error)
	CancelListing(ctx context.Context, in *CancelListingRequest, opts ...grpc.CallOption) (*CancelListingReply, error)
}

type marketplaceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketplaceClient(cc grpc.ClientConnInterface) MarketplaceClient {
	return &marketplaceClient{cc}
}

func (c *marketplaceClient) CreateListing(ctx context.Context, in *CreateListingRequest, opts ...grpc.CallOption) (*CreateListingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateListingReply)
	err := c.cc.Invoke(ctx, Marketplace_CreateListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceClient) GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListingReply)
	err := c.cc.Invoke(ctx, Marketplace_GetListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceClient) ListActiveListings(ctx context.Context, in *ListActiveListingsRequest, opts ...grpc.CallOption) (*ListActiveListingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveListingsReply)
	err := c.cc.Invoke(ctx, Marketplace_ListActiveListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceClient) ListEventListings(ctx context.Context, in *ListEventListingsRequest, opts ...grpc.CallOption) (*ListEventListingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventListingsReply)
	err := c.cc.Invoke(ctx, Marketplace_ListEventListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceClient) ListMyListings(ctx context.Context, in *ListMyListingsRequest, opts ...grpc.CallOption) (*ListMyListingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyListingsReply)
	err := c.cc.Invoke(ctx, Marketplace_ListMyListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceClient) ListMyPurchases(ctx context.Context, in *ListMyPurchasesRequest, opts ...grpc.CallOption) (*ListMyPurchasesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyPurchasesReply)
	err := c.cc.Invoke(ctx, Marketplace_ListMyPurchases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceClient) ListTransferHistory(ctx context.Context, in *ListTransferHistoryRequest, opts ...grpc.CallOption) (*ListTransferHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransferHistoryReply)
	err := c.cc.Invoke(ctx, Marketplace_ListTransferHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceClient) BuyListing(ctx context.Context, in *BuyListingRequest, opts ...grpc.CallOption) (*BuyListingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyListingReply)
	err := c.cc.Invoke(ctx, Marketplace_BuyListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceClient) CancelListing(ctx context.Context, in *CancelListingRequest, opts ...grpc.CallOption) (*CancelListingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelListingReply)
	err := c.cc.Invoke(ctx, Marketplace_CancelListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketplaceServer is the server API for Marketplace service.
// All implementations must embed UnimplementedMarketplaceServer
// for forward compatibility.
//
// Marketplace 二手市场服务：挂牌 CRUD + 转让历史查询。
// 卖家/买家身份由网关从 JWT 解析后通过 user_id 字段传入，
// RPC 服务端信任内网调用方，不再做鉴权。
type MarketplaceServer interface {
	CreateListing(context.Context, *CreateListingRequest) (*CreateListingReply, error)
	GetListing(context.Context, *GetListingRequest) (*GetListingReply, error)
	ListActiveListings(context.Context, *ListActiveListingsRequest) (*ListActiveListingsReply, error)
	ListEventListings(context.Context, *ListEventListingsRequest) (*ListEventListingsReply, error)
	ListMyListings(context.Context, *ListMyListingsRequest) (*ListMyListingsReply, error)
	ListMyPurchases(context.Context, *ListMyPurchasesRequest) (*ListMyPurchasesReply, error)
	ListTransferHistory(context.Context, *ListTransferHistoryRequest) (*ListTransferHistoryReply, error)
	BuyListing(context.Context, *BuyListingRequest) (*BuyListingReply, error)
	CancelListing(context.Context, *CancelListingRequest) (*CancelListingReply, error)
	mustEmbedUnimplementedMarketplaceServer()
}

// UnimplementedMarketplaceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketplaceServer struct{}

func (UnimplementedMarketplaceServer) CreateListing(context.Context, *CreateListingRequest) (*CreateListingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateListing not implemented")
}
func (UnimplementedMarketplaceServer) GetListing(context.Context, *GetListingRequest) (*GetListingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListing not implemented")
}
func (UnimplementedMarketplaceServer) ListActiveListings(context.Context, *ListActiveListingsRequest) (*ListActiveListingsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveListings not implemented")
}
func (UnimplementedMarketplaceServer) ListEventListings(context.Context, *ListEventListingsRequest) (*ListEventListingsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEventListings not implemented")
}
func (UnimplementedMarketplaceServer) ListMyListings(context.Context, *ListMyListingsRequest) (*ListMyListingsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyListings not implemented")
}
func (UnimplementedMarketplaceServer) ListMyPurchases(context.Context, *ListMyPurchasesRequest) (*ListMyPurchasesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyPurchases not implemented")
}
func (UnimplementedMarketplaceServer) ListTransferHistory(context.Context, *ListTransferHistoryRequest) (*ListTransferHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTransferHistory not implemented")
}
func (UnimplementedMarketplaceServer) BuyListing(context.Context, *BuyListingRequest) (*BuyListingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BuyListing not implemented")
}
func (UnimplementedMarketplaceServer) CancelListing(context.Context, *CancelListingRequest) (*CancelListingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelListing not implemented")
}
func (UnimplementedMarketplaceServer) mustEmbedUnimplementedMarketplaceServer() {}
func (UnimplementedMarketplaceServer) testEmbeddedByValue()                     {}

// UnsafeMarketplaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketplaceServer will
// result in compilation errors.
type UnsafeMarketplaceServer interface {
	mustEmbedUnimplementedMarketplaceServer()
}

func RegisterMarketplaceServer(s grpc.ServiceRegistrar, srv MarketplaceServer) {
	// If the following call panics, it indicates UnimplementedMarketplaceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Marketplace_ServiceDesc, srv)
}

func _Marketplace_CreateListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).CreateListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_CreateListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).CreateListing(ctx, req.(*CreateListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketplace_GetListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).GetListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_GetListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).GetListing(ctx, req.(*GetListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketplace_ListActiveListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).ListActiveListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_ListActiveListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).ListActiveListings(ctx, req.(*ListActiveListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketplace_ListEventListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).ListEventListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_ListEventListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).ListEventListings(ctx, req.(*ListEventListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketplace_ListMyListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).ListMyListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_ListMyListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).ListMyListings(ctx, req.(*ListMyListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketplace_ListMyPurchases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyPurchasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).ListMyPurchases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_ListMyPurchases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).ListMyPurchases(ctx, req.(*ListMyPurchasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketplace_ListTransferHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransferHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).ListTransferHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_ListTransferHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).ListTransferHistory(ctx, req.(*ListTransferHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketplace_BuyListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).BuyListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_BuyListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).BuyListing(ctx, req.(*BuyListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketplace_CancelListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServer).CancelListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketplace_CancelListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServer).CancelListing(ctx, req.(*CancelListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Marketplace_ServiceDesc is the grpc.ServiceDesc for Marketplace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marketplace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.market.v1.Marketplace",
	HandlerType: (*MarketplaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateListing",
			Handler:    _Marketplace_CreateListing_Handler,
		},
		{
			MethodName: "GetListing",
			Handler:    _Marketplace_GetListing_Handler,
		},
		{
			MethodName: "ListActiveListings",
			Handler:    _Marketplace_ListActiveListings_Handler,
		},
		{
			MethodName: "ListEventListings",
			Handler:    _Marketplace_ListEventListings_Handler,
		},
		{
			MethodName: "ListMyListings",
			Handler:    _Marketplace_ListMyListings_Handler,
		},
		{
			MethodName: "ListMyPurchases",
			Handler:    _Marketplace_ListMyPurchases_Handler,
		},
		{
			MethodName: "ListTransferHistory",
			Handler:    _Marketplace_ListTransferHistory_Handler,
		},
		{
			MethodName: "BuyListing",
			Handler:    _Marketplace_BuyListing_Handler,
		},
		{
			MethodName: "CancelListing",
			Handler:    _Marketplace_CancelListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market/v1/market.proto",
}
