// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: market/v1/market.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      int64                  `protobuf:"varint,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"` // 当前登录用户
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_market_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *CreateListingRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *CreateListingRequest) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *CreateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateListingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	SellerId      int64                  `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingReply) Reset() {
	*x = CreateListingReply{}
	mi := &file_market_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingReply) ProtoMessage() {}

func (x *CreateListingReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingReply.ProtoReflect.Descriptor instead.
func (*CreateListingReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *CreateListingReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateListingReply) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *CreateListingReply) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *CreateListingReply) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateListingReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateListingReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateListingReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// ListingData 挂牌 + 关联票种/活动的展示信息，详情与列表共用。
type ListingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	EventId       int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTitle    string                 `protobuf:"bytes,4,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"`
	TicketName    string                 `protobuf:"bytes,5,opt,name=ticket_name,json=ticketName,proto3" json:"ticket_name,omitempty"`
	SellerId      int64                  `protobuf:"varint,6,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	BuyerId       int64                  `protobuf:"varint,9,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingData) Reset() {
	*x = ListingData{}
	mi := &file_market_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingData) ProtoMessage() {}

func (x *ListingData) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingData.ProtoReflect.Descriptor instead.
func (*ListingData) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *ListingData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingData) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *ListingData) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ListingData) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

func (x *ListingData) GetTicketName() string {
	if x != nil {
		return x.TicketName
	}
	return ""
}

func (x *ListingData) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *ListingData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListingData) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *ListingData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_market_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetListingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *ListingData           `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingReply) Reset() {
	*x = GetListingReply{}
	mi := &file_market_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingReply) ProtoMessage() {}

func (x *GetListingReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingReply.ProtoReflect.Descriptor instead.
func (*GetListingReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *GetListingReply) GetListing() *ListingData {
	if x != nil {
		return x.Listing
	}
	return nil
}

type ListActiveListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveListingsRequest) Reset() {
	*x = ListActiveListingsRequest{}
	mi := &file_market_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveListingsRequest) ProtoMessage() {}

func (x *ListActiveListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveListingsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveListingsRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *ListActiveListingsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActiveListingsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListActiveListingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ListingData         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveListingsReply) Reset() {
	*x = ListActiveListingsReply{}
	mi := &file_market_v1_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveListingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveListingsReply) ProtoMessage() {}

func (x *ListActiveListingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveListingsReply.ProtoReflect.Descriptor instead.
func (*ListActiveListingsReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{6}
}

func (x *ListActiveListingsReply) GetList() []*ListingData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListActiveListingsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListEventListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventListingsRequest) Reset() {
	*x = ListEventListingsRequest{}
	mi := &file_market_v1_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventListingsRequest) ProtoMessage() {}

func (x *ListEventListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventListingsRequest.ProtoReflect.Descriptor instead.
func (*ListEventListingsRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventListingsRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ListEventListingsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEventListingsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListEventListingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ListingData         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventListingsReply) Reset() {
	*x = ListEventListingsReply{}
	mi := &file_market_v1_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventListingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventListingsReply) ProtoMessage() {}

func (x *ListEventListingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventListingsReply.ProtoReflect.Descriptor instead.
func (*ListEventListingsReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{8}
}

func (x *ListEventListingsReply) GetList() []*ListingData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListEventListingsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListMyListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      int64                  `protobuf:"varint,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"` // 当前登录用户
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyListingsRequest) Reset() {
	*x = ListMyListingsRequest{}
	mi := &file_market_v1_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyListingsRequest) ProtoMessage() {}

func (x *ListMyListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyListingsRequest.ProtoReflect.Descriptor instead.
func (*ListMyListingsRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{9}
}

func (x *ListMyListingsRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *ListMyListingsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyListingsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMyListingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ListingData         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyListingsReply) Reset() {
	*x = ListMyListingsReply{}
	mi := &file_market_v1_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyListingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyListingsReply) ProtoMessage() {}

func (x *ListMyListingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyListingsReply.ProtoReflect.Descriptor instead.
func (*ListMyListingsReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{10}
}

func (x *ListMyListingsReply) GetList() []*ListingData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListMyListingsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListMyPurchasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerId       int64                  `protobuf:"varint,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"` // 当前登录用户
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyPurchasesRequest) Reset() {
	*x = ListMyPurchasesRequest{}
	mi := &file_market_v1_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyPurchasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyPurchasesRequest) ProtoMessage() {}

func (x *ListMyPurchasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyPurchasesRequest.ProtoReflect.Descriptor instead.
func (*ListMyPurchasesRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{11}
}

func (x *ListMyPurchasesRequest) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *ListMyPurchasesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyPurchasesRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMyPurchasesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ListingData         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyPurchasesReply) Reset() {
	*x = ListMyPurchasesReply{}
	mi := &file_market_v1_market_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyPurchasesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyPurchasesReply) ProtoMessage() {}

func (x *ListMyPurchasesReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyPurchasesReply.ProtoReflect.Descriptor instead.
func (*ListMyPurchasesReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{12}
}

func (x *ListMyPurchasesReply) GetList() []*ListingData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListMyPurchasesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TransferHistoryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int64                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TransferType  string                 `protobuf:"bytes,6,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferHistoryData) Reset() {
	*x = TransferHistoryData{}
	mi := &file_market_v1_market_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferHistoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHistoryData) ProtoMessage() {}

func (x *TransferHistoryData) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHistoryData.ProtoReflect.Descriptor instead.
func (*TransferHistoryData) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{13}
}

func (x *TransferHistoryData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferHistoryData) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *TransferHistoryData) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *TransferHistoryData) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *TransferHistoryData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferHistoryData) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *TransferHistoryData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TransferHistoryData) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TransferHistoryData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListTransferHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前登录用户，查自己买入或卖出的记录
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransferHistoryRequest) Reset() {
	*x = ListTransferHistoryRequest{}
	mi := &file_market_v1_market_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransferHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransferHistoryRequest) ProtoMessage() {}

func (x *ListTransferHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransferHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListTransferHistoryRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{14}
}

func (x *ListTransferHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTransferHistoryRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransferHistoryRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListTransferHistoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TransferHistoryData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransferHistoryReply) Reset() {
	*x = ListTransferHistoryReply{}
	mi := &file_market_v1_market_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransferHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransferHistoryReply) ProtoMessage() {}

func (x *ListTransferHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransferHistoryReply.ProtoReflect.Descriptor instead.
func (*ListTransferHistoryReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{15}
}

func (x *ListTransferHistoryReply) GetList() []*TransferHistoryData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTransferHistoryReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BuyListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          // 挂牌 ID
	BuyerId       int64                  `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"` // 当前登录用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyListingRequest) Reset() {
	*x = BuyListingRequest{}
	mi := &file_market_v1_market_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyListingRequest) ProtoMessage() {}

func (x *BuyListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyListingRequest.ProtoReflect.Descriptor instead.
func (*BuyListingRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{16}
}

func (x *BuyListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuyListingRequest) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

type BuyListingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyListingReply) Reset() {
	*x = BuyListingReply{}
	mi := &file_market_v1_market_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyListingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyListingReply) ProtoMessage() {}

func (x *BuyListingReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyListingReply.ProtoReflect.Descriptor instead.
func (*BuyListingReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{17}
}

func (x *BuyListingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                             // 挂牌 ID
	SellerId      int64                  `protobuf:"varint,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"` // 当前登录用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelListingRequest) Reset() {
	*x = CancelListingRequest{}
	mi := &file_market_v1_market_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelListingRequest) ProtoMessage() {}

func (x *CancelListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelListingRequest.ProtoReflect.Descriptor instead.
func (*CancelListingRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{18}
}

func (x *CancelListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CancelListingRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

type CancelListingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelListingReply) Reset() {
	*x = CancelListingReply{}
	mi := &file_market_v1_market_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelListingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelListingReply) ProtoMessage() {}

func (x *CancelListingReply) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelListingReply.ProtoReflect.Descriptor instead.
func (*CancelListingReply) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{19}
}

func (x *CancelListingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_market_v1_market_proto protoreflect.FileDescriptor

const file_market_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x16market/v1/market.proto\x12\rapi.market.v1\"\x88\x01\n" +
	"\x14CreateListingRequest\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\x03R\bsellerId\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xcd\x01\n" +
	"\x12CreateListingReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\x03R\bsellerId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\xbe\x02\n" +
	"\vListingData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12\x1f\n" +
	"\vevent_title\x18\x04 \x01(\tR\n" +
	"eventTitle\x12\x1f\n" +
	"\vticket_name\x18\x05 \x01(\tR\n" +
	"ticketName\x12\x1b\n" +
	"\tseller_id\x18\x06 \x01(\x03R\bsellerId\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x19\n" +
	"\bbuyer_id\x18\t \x01(\x03R\abuyerId\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"#\n" +
	"\x11GetListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x0fGetListingReply\x124\n" +
	"\alisting\x18\x01 \x01(\v2\x1a.api.market.v1.ListingDataR\alisting\"C\n" +
	"\x19ListActiveListingsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"_\n" +
	"\x17ListActiveListingsReply\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.api.market.v1.ListingDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"]\n" +
	"\x18ListEventListingsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"^\n" +
	"\x16ListEventListingsReply\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.api.market.v1.ListingDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\\\n" +
	"\x15ListMyListingsRequest\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\x03R\bsellerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"[\n" +
	"\x13ListMyListingsReply\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.api.market.v1.ListingDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"[\n" +
	"\x16ListMyPurchasesRequest\x12\x19\n" +
	"\bbuyer_id\x18\x01 \x01(\x03R\abuyerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\\\n" +
	"\x14ListMyPurchasesReply\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.api.market.v1.ListingDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x8c\x02\n" +
	"\x13TransferHistoryData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x03R\bticketId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\x03R\btoUserId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rtransfer_type\x18\x06 \x01(\tR\ftransferType\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"]\n" +
	"\x1aListTransferHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"h\n" +
	"\x18ListTransferHistoryReply\x126\n" +
	"\x04list\x18\x01 \x03(\v2\".api.market.v1.TransferHistoryDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\">\n" +
	"\x11BuyListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x03R\abuyerId\"+\n" +
	"\x0fBuyListingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\x14CancelListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\x03R\bsellerId\".\n" +
	"\x12CancelListingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd2\x06\n" +
	"\vMarketplace\x12W\n" +
	"\rCreateListing\x12#.api.market.v1.CreateListingRequest\x1a!.api.market.v1.CreateListingReply\x12N\n" +
	"\n" +
	"GetListing\x12 .api.market.v1.GetListingRequest\x1a\x1e.api.market.v1.GetListingReply\x12f\n" +
	"\x12ListActiveListings\x12(.api.market.v1.ListActiveListingsRequest\x1a&.api.market.v1.ListActiveListingsReply\x12c\n" +
	"\x11ListEventListings\x12'.api.market.v1.ListEventListingsRequest\x1a%.api.market.v1.ListEventListingsReply\x12Z\n" +
	"\x0eListMyListings\x12$.api.market.v1.ListMyListingsRequest\x1a\".api.market.v1.ListMyListingsReply\x12]\n" +
	"\x0fListMyPurchases\x12%.api.market.v1.ListMyPurchasesRequest\x1a#.api.market.v1.ListMyPurchasesReply\x12i\n" +
	"\x13ListTransferHistory\x12).api.market.v1.ListTransferHistoryRequest\x1a'.api.market.v1.ListTransferHistoryReply\x12N\n" +
	"\n" +
	"BuyListing\x12 .api.market.v1.BuyListingRequest\x1a\x1e.api.market.v1.BuyListingReply\x12W\n" +
	"\rCancelListing\x12#.api.market.v1.CancelListingRequest\x1a!.api.market.v1.CancelListingReplyB*\n" +
	"\rapi.market.v1P\x01Z\x17market/api/market/v1;v1b\x06proto3"

var (
	file_market_v1_market_proto_rawDescOnce sync.Once
	file_market_v1_market_proto_rawDescData []byte
)

func file_market_v1_market_proto_rawDescGZIP() []byte {
	file_market_v1_market_proto_rawDescOnce.Do(func() {
		file_market_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)))
	})
	return file_market_v1_market_proto_rawDescData
}

var file_market_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_market_v1_market_proto_goTypes = []any{
	(*CreateListingRequest)(nil),       // 0: api.market.v1.CreateListingRequest
	(*CreateListingReply)(nil),         // 1: api.market.v1.CreateListingReply
	(*ListingData)(nil),                // 2: api.market.v1.ListingData
	(*GetListingRequest)(nil),          // 3: api.market.v1.GetListingRequest
	(*GetListingReply)(nil),            // 4: api.market.v1.GetListingReply
	(*ListActiveListingsRequest)(nil),  // 5: api.market.v1.ListActiveListingsRequest
	(*ListActiveListingsReply)(nil),    // 6: api.market.v1.ListActiveListingsReply
	(*ListEventListingsRequest)(nil),   // 7: api.market.v1.ListEventListingsRequest
	(*ListEventListingsReply)(nil),     // 8: api.market.v1.ListEventListingsReply
	(*ListMyListingsRequest)(nil),      // 9: api.market.v1.ListMyListingsRequest
	(*ListMyListingsReply)(nil),        // 10: api.market.v1.ListMyListingsReply
	(*ListMyPurchasesRequest)(nil),     // 11: api.market.v1.ListMyPurchasesRequest
	(*ListMyPurchasesReply)(nil),       // 12: api.market.v1.ListMyPurchasesReply
	(*TransferHistoryData)(nil),        // 13: api.market.v1.TransferHistoryData
	(*ListTransferHistoryRequest)(nil), // 14: api.market.v1.ListTransferHistoryRequest
	(*ListTransferHistoryReply)(nil),   // 15: api.market.v1.ListTransferHistoryReply
	(*BuyListingRequest)(nil),          // 16: api.market.v1.BuyListingRequest
	(*BuyListingReply)(nil),            // 17: api.market.v1.BuyListingReply
	(*CancelListingRequest)(nil),       // 18: api.market.v1.CancelListingRequest
	(*CancelListingReply)(nil),         // 19: api.market.v1.CancelListingReply
}
var file_market_v1_market_proto_depIdxs = []int32{
	2,  // 0: api.market.v1.GetListingReply.listing:type_name -> api.market.v1.ListingData
	2,  // 1: api.market.v1.ListActiveListingsReply.list:type_name -> api.market.v1.ListingData
	2,  // 2: api.market.v1.ListEventListingsReply.list:type_name -> api.market.v1.ListingData
	2,  // 3: api.market.v1.ListMyListingsReply.list:type_name -> api.market.v1.ListingData
	2,  // 4: api.market.v1.ListMyPurchasesReply.list:type_name -> api.market.v1.ListingData
	13, // 5: api.market.v1.ListTransferHistoryReply.list:type_name -> api.market.v1.TransferHistoryData
	0,  // 6: api.market.v1.Marketplace.CreateListing:input_type -> api.market.v1.CreateListingRequest
	3,  // 7: api.market.v1.Marketplace.GetListing:input_type -> api.market.v1.GetListingRequest
	5,  // 8: api.market.v1.Marketplace.ListActiveListings:input_type -> api.market.v1.ListActiveListingsRequest
	7,  // 9: api.market.v1.Marketplace.ListEventListings:input_type -> api.market.v1.ListEventListingsRequest
	9,  // 10: api.market.v1.Marketplace.ListMyListings:input_type -> api.market.v1.ListMyListingsRequest
	11, // 11: api.market.v1.Marketplace.ListMyPurchases:input_type -> api.market.v1.ListMyPurchasesRequest
	14, // 12: api.market.v1.Marketplace.ListTransferHistory:input_type -> api.market.v1.ListTransferHistoryRequest
	16, // 13: api.market.v1.Marketplace.BuyListing:input_type -> api.market.v1.BuyListingRequest
	18, // 14: api.market.v1.Marketplace.CancelListing:input_type -> api.market.v1.CancelListingRequest
	1,  // 15: api.market.v1.Marketplace.CreateListing:output_type -> api.market.v1.CreateListingReply
	4,  // 16: api.market.v1.Marketplace.GetListing:output_type -> api.market.v1.GetListingReply
	6,  // 17: api.market.v1.Marketplace.ListActiveListings:output_type -> api.market.v1.ListActiveListingsReply
	8,  // 18: api.market.v1.Marketplace.ListEventListings:output_type -> api.market.v1.ListEventListingsReply
	10, // 19: api.market.v1.Marketplace.ListMyListings:output_type -> api.market.v1.ListMyListingsReply
	12, // 20: api.market.v1.Marketplace.ListMyPurchases:output_type -> api.market.v1.ListMyPurchasesReply
	15, // 21: api.market.v1.Marketplace.ListTransferHistory:output_type -> api.market.v1.ListTransferHistoryReply
	17, // 22: api.market.v1.Marketplace.BuyListing:output_type -> api.market.v1.BuyListingReply
	19, // 23: api.market.v1.Marketplace.CancelListing:output_type -> api.market.v1.CancelListingReply
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_market_v1_market_proto_init() }
func file_market_v1_market_proto_init() {
	if File_market_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_v1_market_proto_goTypes,
		DependencyIndexes: file_market_v1_market_proto_depIdxs,
		MessageInfos:      file_market_v1_market_proto_msgTypes,
	}.Build()
	File_market_v1_market_proto = out.File
	file_market_v1_market_proto_goTypes = nil
	file_market_v1_market_proto_depIdxs = nil
}
