// Code generated by hertz generator.

package ticket_type

import (
	"getway/mvw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return mvw.AuthMiddleware()
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtickettypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ticket_typesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettickettypeMw() []app.HandlerFunc {
	// your code...
	return nil
}
